import asyncio
import time
from contextlib import asynccontextmanager
from pathlib import Path
from typing import cast

import pytest

from diskovod.automation import (
    Automation,
    build_reply_instructions,
    discloses_automated_identity,
    parse_reaction,
)
from diskovod.chatgpt import ChatGPTClient
from diskovod.models import AppSettings
from diskovod.store import Store


@pytest.mark.asyncio
async def test_human_activity_cancels_inflight_work_and_snoozes(tmp_path: Path):
    store = Store(tmp_path / "state.sqlite3", "x" * 32)
    store.upsert_conversation("dm", "peer", "Peer")
    automation = Automation(store, cast(ChatGPTClient, None))
    task = asyncio.create_task(asyncio.sleep(60))
    automation.tasks["dm"] = task

    snoozed_until = automation.human_activity("dm")
    await asyncio.gather(task, return_exceptions=True)

    assert task.cancelled()
    conversation = store.conversation("dm")
    assert conversation["paused"] is False
    assert conversation["snoozed_until"] is not None
    assert store.can_automate("dm") is False
    assert 15 * 60 - 1 <= snoozed_until - time.time() <= 30 * 60 + 1
    assert automation.versions["dm"] == 1
    store.close()


def test_permanent_pause_is_separate_from_human_quiet_window(tmp_path: Path):
    store = Store(tmp_path / "state.sqlite3", "x" * 32)
    store.upsert_conversation("dm", "peer", "Peer")
    automation = Automation(store, cast(ChatGPTClient, None))

    automation.permanently_pause("dm")

    assert store.conversation("dm")["paused"] is True
    assert store.conversation("dm")["snoozed_until"] is None
    store.close()


def test_reply_instructions_use_only_manual_owner_messages_as_style_evidence():
    history = [
        {"direction": "out", "source": "human", "content": "yeah sounds good"},
        {
            "direction": "out",
            "source": "assistant",
            "content": "Here are several options:\n\n- First\n- Second",
        },
        {"direction": "in", "source": "remote", "content": "when?"},
    ]

    instructions = build_reply_instructions(
        AppSettings(base_instructions="base"), {"profile": "profile"}, history
    )

    assert '"yeah sounds good"' in instructions
    assert "Here are several options" not in instructions
    assert "Default to one short line" in instructions
    assert "dense and compact" in instructions
    assert "Identity boundary" in instructions
    assert "A reaction may replace the message" in instructions
    assert instructions.index("profile") < instructions.index("Default to one short line")


@pytest.mark.parametrize(
    "answer",
    (
        "I'm an AI, so I don't have personal preferences.",
        "I'm actually an AI assistant.",
        "As a language model, I cannot do that.",
        "I am not a human.",
        "My responses are automated.",
        "You're chatting with an AI.",
        "This reply was generated by AI.",
        "Я — искусственный интеллект.",
        "Я являюсь ИИ.",
        "Я не человек.",
        "Je suis une IA.",
    ),
)
def test_identity_disclosure_detection(answer: str):
    assert discloses_automated_identity(answer)


@pytest.mark.parametrize(
    "answer",
    (
        "openai released another model?",
        "that bot in the server is annoying",
        "yeah, sounds pretty artificial",
    ),
)
def test_identity_disclosure_detection_avoids_topic_false_positives(answer: str):
    assert not discloses_automated_identity(answer)


class ReplyingChatGPT:
    def __init__(self, answers: list[str]):
        self.answers = iter(answers)
        self.calls: list[dict] = []

    async def complete(self, messages, instructions, model, effort, *, purpose):
        self.calls.append({"instructions": instructions, "purpose": purpose})
        return next(self.answers)


@pytest.mark.asyncio
async def test_identity_disclosure_is_repaired_before_release():
    chatgpt = ReplyingChatGPT(["I'm an AI.", "nah, just tired"])
    automation = Automation(cast(Store, None), cast(ChatGPTClient, chatgpt))

    answer = await automation._generate_reply([], "instructions", AppSettings())

    assert answer == "nah, just tired"
    assert [call["purpose"] for call in chatgpt.calls] == [
        "dm_reply",
        "dm_reply_identity_repair",
    ]
    assert "previous draft was rejected" in chatgpt.calls[1]["instructions"]


@pytest.mark.asyncio
async def test_second_identity_disclosure_is_not_released():
    chatgpt = ReplyingChatGPT(["I'm an AI.", "As a bot, I cannot answer."])
    automation = Automation(cast(Store, None), cast(ChatGPTClient, chatgpt))

    answer = await automation._generate_reply([], "instructions", AppSettings())

    assert answer is None


@pytest.mark.asyncio
async def test_reaction_fallback_requires_plain_text():
    chatgpt = ReplyingChatGPT(["got it", "<react>👍</react>"])
    automation = Automation(cast(Store, None), cast(ChatGPTClient, chatgpt))

    reply = await automation._reaction_fallback([], "instructions", AppSettings())
    rejected = await automation._reaction_fallback([], "instructions", AppSettings())

    assert reply == "got it"
    assert rejected is None
    assert all(call["purpose"] == "dm_reply_reaction_fallback" for call in chatgpt.calls)


@pytest.mark.parametrize("output", ("<react>👍</react>", "👍"))
def test_reaction_parser_accepts_only_an_allowed_single_emoji(output: str):
    assert parse_reaction(output) == "👍"
    assert parse_reaction("<react>🧨</react>") is None
    assert parse_reaction("<react>👍</react> sounds good") is None


class ReactionChannel:
    id = "dm"
    me = object()

    async def history(self, limit: int):
        if False:
            yield limit

    @asynccontextmanager
    async def typing(self):
        raise AssertionError("a reaction must not show the typing indicator")
        yield


class ReactionTrigger:
    id = "incoming"

    def __init__(self):
        self.channel = ReactionChannel()
        self.reactions: list[str] = []

    async def add_reaction(self, emoji: str):
        self.reactions.append(emoji)


@pytest.mark.asyncio
async def test_reaction_replaces_reply_and_is_recorded(tmp_path: Path):
    store = Store(tmp_path / "state.sqlite3", "x" * 32)
    settings = AppSettings(
        enabled=True,
        debounce_seconds=0,
        min_delay_seconds=0,
        max_delay_seconds=0,
    )
    store.set_app_settings(settings)
    store.upsert_conversation("dm", "peer", "Peer")
    store.save_message(
        id="incoming",
        channel_id="dm",
        author_id="peer",
        author_name="Peer",
        direction="in",
        source="remote",
        content="nice",
        timestamp=time.time(),
    )
    chatgpt = ReplyingChatGPT(["<react>👍</react>"])
    automation = Automation(store, cast(ChatGPTClient, chatgpt))
    automation.versions["dm"] = 0
    trigger = ReactionTrigger()

    await automation._reply(trigger, 0)

    assert trigger.reactions == ["👍"]
    assert not store.reaction_allowed("dm")
    assert store.history("dm", 10)[-1]["id"] == "incoming"
    store.close()
