from __future__ import annotations

from .localization import normalize_locale


def _text(en: str, ru: str, uk: str, ja: str, zh: str, de: str, fr: str) -> dict[str, str]:
    return {"en": en, "ru": ru, "uk": uk, "ja": ja, "zh": zh, "de": de, "fr": fr}


# Short, stable keys keep translations out of the Jinja template and make missing
# translations fall back to English instead of breaking the admin page.
UI_TEXT: dict[str, dict[str, str]] = {
    "skip": {
        "en": "Skip to content",
        "ru": "Перейти к содержимому",
        "uk": "Перейти до вмісту",
        "ja": "コンテンツへ移動",
        "de": "Zum Inhalt springen",
        "fr": "Aller au contenu",
        "zh": "跳到内容",
    },
    "admin_navigation": {
        "en": "Admin navigation",
        "ru": "Навигация администратора",
        "uk": "Навігація адміністратора",
        "ja": "管理画面ナビゲーション",
        "de": "Admin-Navigation",
        "fr": "Navigation d’administration",
        "zh": "管理导航",
    },
    "connections": {
        "en": "Connections",
        "ru": "Подключения",
        "uk": "Підключення",
        "ja": "接続",
        "de": "Verbindungen",
        "fr": "Connexions",
        "zh": "连接",
    },
    "personality": {
        "en": "Personality",
        "ru": "Личность",
        "uk": "Особистість",
        "ja": "人物像",
        "de": "Persönlichkeit",
        "fr": "Personnalité",
        "zh": "性格",
    },
    "behavior": {
        "en": "Behavior",
        "ru": "Поведение",
        "uk": "Поведінка",
        "ja": "動作",
        "de": "Verhalten",
        "fr": "Comportement",
        "zh": "行为",
    },
    "usage": {
        "en": "Usage",
        "ru": "Использование",
        "uk": "Використання",
        "ja": "使用状況",
        "de": "Nutzung",
        "fr": "Utilisation",
        "zh": "使用情况",
    },
    "conversations": {
        "en": "Conversations",
        "ru": "Диалоги",
        "uk": "Розмови",
        "ja": "会話",
        "de": "Unterhaltungen",
        "fr": "Conversations",
        "zh": "对话",
    },
    "database": {
        "en": "Database",
        "ru": "База данных",
        "uk": "База даних",
        "ja": "データベース",
        "de": "Datenbank",
        "fr": "Base de données",
        "zh": "数据库",
    },
    "tagline_label": {
        "en": "Private DM automation",
        "ru": "Автоматизация личных сообщений",
        "uk": "Автоматизація приватних повідомлень",
        "ja": "DM自動化",
        "de": "Automatisierung privater Nachrichten",
        "fr": "Automatisation des messages privés",
        "zh": "私信自动化",
    },
    "tagline": {
        "en": "Natural replies that step aside whenever you join the conversation.",
        "ru": "Естественные ответы, которые уступают место, когда вы вступаете в разговор.",
        "uk": "Природні відповіді, що поступаються місцем, коли ви долучаєтеся до розмови.",
        "ja": "あなたが会話に加わると、自動返信は自然に止まります。",
        "de": "Natürliche Antworten, die pausieren, sobald du dich einschaltest.",
        "fr": "Des réponses naturelles qui s’effacent dès que vous rejoignez la conversation.",
        "zh": "当你加入对话时，自动回复会自然让位。",
    },
    "automation_enabled": {
        "en": "Automation enabled",
        "ru": "Автоматизация включена",
        "uk": "Автоматизацію ввімкнено",
        "ja": "自動化は有効です",
        "de": "Automatisierung aktiviert",
        "fr": "Automatisation activée",
        "zh": "自动化已启用",
    },
    "automation_disabled": {
        "en": "Automation disabled",
        "ru": "Автоматизация выключена",
        "uk": "Автоматизацію вимкнено",
        "ja": "自動化は無効です",
        "de": "Automatisierung deaktiviert",
        "fr": "Automatisation désactivée",
        "zh": "自动化已禁用",
    },
    "active": {
        "en": "Active",
        "ru": "Активно",
        "uk": "Активно",
        "ja": "使用中",
        "de": "Aktiv",
        "fr": "Actif",
        "zh": "使用中",
    },
    "connected": {
        "en": "Connected",
        "ru": "Подключено",
        "uk": "Підключено",
        "ja": "接続済み",
        "de": "Verbunden",
        "fr": "Connecté",
        "zh": "已连接",
    },
    "not_connected": {
        "en": "Not connected",
        "ru": "Не подключено",
        "uk": "Не підключено",
        "ja": "未接続",
        "de": "Nicht verbunden",
        "fr": "Non connecté",
        "zh": "未连接",
    },
    "configured": {
        "en": "Configured",
        "ru": "Настроено",
        "uk": "Налаштовано",
        "ja": "設定済み",
        "de": "Konfiguriert",
        "fr": "Configuré",
        "zh": "已配置",
    },
    "not_configured": {
        "en": "Not configured",
        "ru": "Не настроено",
        "uk": "Не налаштовано",
        "ja": "未設定",
        "de": "Nicht konfiguriert",
        "fr": "Non configuré",
        "zh": "未配置",
    },
    "chatgpt_subscription": {
        "en": "ChatGPT subscription",
        "ru": "Подписка ChatGPT",
        "uk": "Підписка ChatGPT",
        "ja": "ChatGPTサブスクリプション",
        "de": "ChatGPT-Abonnement",
        "fr": "Abonnement ChatGPT",
        "zh": "ChatGPT 订阅",
    },
    "custom_api": {
        "en": "OpenAI-compatible API",
        "ru": "OpenAI-совместимый API",
        "uk": "OpenAI-сумісний API",
        "ja": "OpenAI互換API",
        "de": "OpenAI-kompatible API",
        "fr": "API compatible OpenAI",
        "zh": "OpenAI 兼容 API",
    },
    "discord": {
        "en": "Discord",
        "ru": "Discord",
        "uk": "Discord",
        "ja": "Discord",
        "de": "Discord",
        "fr": "Discord",
        "zh": "Discord",
    },
    "disconnect": {
        "en": "Disconnect",
        "ru": "Отключить",
        "uk": "Відключити",
        "ja": "切断",
        "de": "Trennen",
        "fr": "Déconnecter",
        "zh": "断开连接",
    },
    "sign_in_chatgpt": {
        "en": "Sign in with ChatGPT",
        "ru": "Войти через ChatGPT",
        "uk": "Увійти через ChatGPT",
        "ja": "ChatGPTでログイン",
        "de": "Mit ChatGPT anmelden",
        "fr": "Se connecter avec ChatGPT",
        "zh": "使用 ChatGPT 登录",
    },
    "save_connect": {
        "en": "Save token and connect",
        "ru": "Сохранить токен и подключиться",
        "uk": "Зберегти токен і підключитися",
        "ja": "トークンを保存して接続",
        "de": "Token speichern und verbinden",
        "fr": "Enregistrer le jeton et se connecter",
        "zh": "保存令牌并连接",
    },
    "personality_cache": {
        "en": "Personality cache",
        "ru": "Кэш личности",
        "uk": "Кеш особистості",
        "ja": "人物像キャッシュ",
        "de": "Persönlichkeits-Cache",
        "fr": "Cache de personnalité",
        "zh": "性格缓存",
    },
    "cached": {
        "en": "Cached",
        "ru": "Сохранено",
        "uk": "Збережено",
        "ja": "保存済み",
        "de": "Gespeichert",
        "fr": "En cache",
        "zh": "已缓存",
    },
    "empty": {
        "en": "Empty",
        "ru": "Пусто",
        "uk": "Порожньо",
        "ja": "空",
        "de": "Leer",
        "fr": "Vide",
        "zh": "空",
    },
    "reply_behavior": {
        "en": "Reply behavior",
        "ru": "Поведение ответов",
        "uk": "Поведінка відповідей",
        "ja": "返信動作",
        "de": "Antwortverhalten",
        "fr": "Comportement des réponses",
        "zh": "回复行为",
    },
    "admin_language": {
        "en": "Admin interface language",
        "ru": "Язык панели администратора",
        "uk": "Мова панелі адміністратора",
        "ja": "管理画面の言語",
        "de": "Sprache der Admin-Oberfläche",
        "fr": "Langue de l’interface d’administration",
        "zh": "管理界面语言",
    },
    "prompt_language": {
        "en": "Built-in prompt language",
        "ru": "Язык встроенных промптов",
        "uk": "Мова вбудованих промптів",
        "ja": "組み込みプロンプトの言語",
        "de": "Sprache der integrierten Prompts",
        "fr": "Langue des prompts intégrés",
        "zh": "内置提示词语言",
    },
    "prompt_language_help": {
        "en": "Controls built-in assistant, reaction, attachment, and personality prompts. Custom base instructions are preserved.",
        "ru": "Определяет язык встроенных инструкций ассистента, реакций, вложений и профиля. Пользовательские базовые инструкции сохраняются.",
        "uk": "Визначає мову вбудованих інструкцій асистента, реакцій, вкладень і профілю. Власні базові інструкції зберігаються.",
        "ja": "アシスタント、リアクション、添付、人物像の組み込みプロンプトに使います。独自の基本指示は保持されます。",
        "de": "Steuert die integrierten Assistenten-, Reaktions-, Anhangs- und Persönlichkeits-Prompts. Eigene Basisanweisungen bleiben erhalten.",
        "fr": "Contrôle les prompts intégrés de l’assistant, des réactions, des pièces jointes et de la personnalité. Les instructions personnalisées sont conservées.",
        "zh": "控制助手、回应表情、附件和性格分析的内置提示词。自定义基础指令会保留。",
    },
    "enable_replies": {
        "en": "Enable automated replies",
        "ru": "Включить автоматические ответы",
        "uk": "Увімкнути автоматичні відповіді",
        "ja": "自動返信を有効にする",
        "de": "Automatische Antworten aktivieren",
        "fr": "Activer les réponses automatiques",
        "zh": "启用自动回复",
    },
    "silent_replies": {
        "en": "Send generated replies without notifications",
        "ru": "Отправлять ответы без уведомлений",
        "uk": "Надсилати відповіді без сповіщень",
        "ja": "通知なしで返信を送信",
        "de": "Generierte Antworten ohne Benachrichtigung senden",
        "fr": "Envoyer les réponses sans notification",
        "zh": "发送回复时不触发通知",
    },
    "robot_prefix": {
        "en": "Prefix generated replies with 🤖",
        "ru": "Добавлять 🤖 перед ответами",
        "uk": "Додавати 🤖 перед відповідями",
        "ja": "返信の先頭に🤖を付ける",
        "de": "Generierten Antworten 🤖 voranstellen",
        "fr": "Préfixer les réponses avec 🤖",
        "zh": "在自动回复前添加 🤖",
    },
    "new_conversation_default": {
        "en": "New conversation default",
        "ru": "Настройка новых диалогов",
        "uk": "Налаштування нових розмов",
        "ja": "新しい会話の既定値",
        "de": "Standard für neue Unterhaltungen",
        "fr": "Valeur par défaut des nouvelles conversations",
        "zh": "新对话默认设置",
    },
    "provider": {
        "en": "Provider",
        "ru": "Провайдер",
        "uk": "Провайдер",
        "ja": "プロバイダー",
        "de": "Anbieter",
        "fr": "Fournisseur",
        "zh": "提供商",
    },
    "model": {
        "en": "Model",
        "ru": "Модель",
        "uk": "Модель",
        "ja": "モデル",
        "de": "Modell",
        "fr": "Modèle",
        "zh": "模型",
    },
    "reasoning": {
        "en": "Reasoning",
        "ru": "Рассуждение",
        "uk": "Міркування",
        "ja": "推論",
        "de": "Schlussfolgern",
        "fr": "Raisonnement",
        "zh": "推理",
    },
    "reply_token_budget": {
        "en": "Reply token budget",
        "ru": "Лимит токенов ответа",
        "uk": "Ліміт токенів відповіді",
        "ja": "返信トークン上限",
        "de": "Tokenbudget der Antwort",
        "fr": "Budget de jetons de réponse",
        "zh": "回复 token 限额",
    },
    "multi_message_replies": {
        "en": "Multi-message replies",
        "ru": "Ответы из нескольких сообщений",
        "uk": "Відповіді з кількох повідомлень",
        "ja": "複数メッセージ返信",
        "de": "Antworten mit mehreren Nachrichten",
        "fr": "Réponses en plusieurs messages",
        "zh": "多消息回复",
    },
    "reply_timing": {
        "en": "Reply timing",
        "ru": "Время ответа",
        "uk": "Час відповіді",
        "ja": "返信タイミング",
        "de": "Antwortzeit",
        "fr": "Temporisation des réponses",
        "zh": "回复时间",
    },
    "quiet_window": {
        "en": "Human activity quiet window",
        "ru": "Пауза после активности человека",
        "uk": "Пауза після активності людини",
        "ja": "手動操作後の休止時間",
        "de": "Ruhefenster nach menschlicher Aktivität",
        "fr": "Pause après une activité humaine",
        "zh": "手动活动后的静默时段",
    },
    "owner_details": {
        "en": "Owner details",
        "ru": "Данные владельца",
        "uk": "Дані власника",
        "ja": "所有者の情報",
        "de": "Angaben zum Inhaber",
        "fr": "Informations sur le propriétaire",
        "zh": "所有者信息",
    },
    "base_instructions": {
        "en": "Base instructions",
        "ru": "Базовые инструкции",
        "uk": "Базові інструкції",
        "ja": "基本指示",
        "de": "Basisanweisungen",
        "fr": "Instructions de base",
        "zh": "基础指令",
    },
    "save_behavior": {
        "en": "Save behavior",
        "ru": "Сохранить настройки",
        "uk": "Зберегти налаштування",
        "ja": "動作設定を保存",
        "de": "Verhalten speichern",
        "fr": "Enregistrer le comportement",
        "zh": "保存行为设置",
    },
    "model_token_usage": {
        "en": "Model token usage",
        "ru": "Использование токенов",
        "uk": "Використання токенів",
        "ja": "モデルのトークン使用量",
        "de": "Token-Nutzung des Modells",
        "fr": "Utilisation des jetons du modèle",
        "zh": "模型 token 使用量",
    },
    "force_reply": {
        "en": "Force reply",
        "ru": "Ответить принудительно",
        "uk": "Відповісти примусово",
        "ja": "強制返信",
        "de": "Antwort erzwingen",
        "fr": "Forcer une réponse",
        "zh": "强制回复",
    },
    "enable_automation": {
        "en": "Enable automation",
        "ru": "Включить автоматизацию",
        "uk": "Увімкнути автоматизацію",
        "ja": "自動化を有効にする",
        "de": "Automatisierung aktivieren",
        "fr": "Activer l’automatisation",
        "zh": "启用自动化",
    },
    "disable_automation": {
        "en": "Disable automation",
        "ru": "Отключить автоматизацию",
        "uk": "Вимкнути автоматизацію",
        "ja": "自動化を無効にする",
        "de": "Automatisierung deaktivieren",
        "fr": "Désactiver l’automatisation",
        "zh": "禁用自动化",
    },
    "database_explorer": {
        "en": "Database explorer",
        "ru": "Обзор базы данных",
        "uk": "Огляд бази даних",
        "ja": "データベース参照",
        "de": "Datenbank-Explorer",
        "fr": "Explorateur de base de données",
        "zh": "数据库浏览器",
    },
    "search": {
        "en": "Search",
        "ru": "Поиск",
        "uk": "Пошук",
        "ja": "検索",
        "de": "Suchen",
        "fr": "Rechercher",
        "zh": "搜索",
    },
    "clear": {
        "en": "Clear",
        "ru": "Очистить",
        "uk": "Очистити",
        "ja": "クリア",
        "de": "Leeren",
        "fr": "Effacer",
        "zh": "清除",
    },
    "previous": {
        "en": "Previous",
        "ru": "Назад",
        "uk": "Назад",
        "ja": "前へ",
        "de": "Zurück",
        "fr": "Précédent",
        "zh": "上一页",
    },
    "next": {
        "en": "Next",
        "ru": "Далее",
        "uk": "Далі",
        "ja": "次へ",
        "de": "Weiter",
        "fr": "Suivant",
        "zh": "下一页",
    },
    "settings_saved": {
        "en": "Automation settings saved",
        "ru": "Настройки автоматизации сохранены",
        "uk": "Налаштування автоматизації збережено",
        "ja": "自動化設定を保存しました",
        "de": "Automatisierungseinstellungen gespeichert",
        "fr": "Paramètres d’automatisation enregistrés",
        "zh": "自动化设置已保存",
    },
    "unknown_locale": {
        "en": "Unknown localization language",
        "ru": "Неизвестный язык локализации",
        "uk": "Невідома мова локалізації",
        "ja": "不明なローカライズ言語です",
        "de": "Unbekannte Lokalisierungssprache",
        "fr": "Langue de localisation inconnue",
        "zh": "未知的本地化语言",
    },
    "escalations": {
        "en": "Owner escalations",
        "ru": "Обращения к владельцу",
        "uk": "Звернення до власника",
        "ja": "所有者へのエスカレーション",
        "de": "Weiterleitungen an den Inhaber",
        "fr": "Transferts au propriétaire",
        "zh": "转交所有者",
    },
    "escalation_count": {
        "en": "{count} active",
        "ru": "Активных: {count}",
        "uk": "Активних: {count}",
        "ja": "{count} 件対応中",
        "de": "{count} aktiv",
        "fr": "{count} actif(s)",
        "zh": "{count} 个处理中",
    },
    "escalation_help": {
        "en": "When someone explicitly asks for the account owner, the assistant acknowledges them, pauses that conversation, and places it here. Closing an escalation keeps automation paused unless you explicitly resume it.",
        "ru": "Если собеседник явно просит связаться с владельцем аккаунта, ассистент подтверждает запрос, приостанавливает автоматизацию в диалоге и добавляет его сюда. После закрытия обращения автоматизация остаётся выключенной, пока вы явно не возобновите её.",
        "uk": "Якщо співрозмовник прямо просить зв’язатися з власником облікового запису, асистент підтверджує запит, призупиняє автоматизацію в розмові та додає її сюди. Після закриття звернення автоматизація лишається вимкненою, доки ви явно її не відновите.",
        "ja": "相手がアカウント所有者への取り次ぎを明示的に求めると、アシスタントが受け付けを伝え、その会話の自動化を停止してここに追加します。エスカレーションを閉じても、明示的に再開しない限り自動化は停止したままです。",
        "de": "Wenn jemand ausdrücklich nach dem Kontoinhaber fragt, bestätigt der Assistent die Anfrage, pausiert die Unterhaltung und legt sie hier ab. Beim Schließen bleibt die Automatisierung pausiert, sofern du sie nicht ausdrücklich fortsetzt.",
        "fr": "Lorsqu’une personne demande explicitement le propriétaire du compte, l’assistant accuse réception, met l’automatisation de cette conversation en pause et l’ajoute ici. Fermer le transfert laisse l’automatisation en pause, sauf si vous la reprenez explicitement.",
        "zh": "当对方明确要求联系账号所有者时，助手会确认请求、暂停该对话并将其放在这里。关闭转交事项后，自动化仍会保持暂停，除非你明确选择恢复。",
    },
    "unknown_peer": {
        "en": "Unknown peer",
        "ru": "Неизвестный собеседник",
        "uk": "Невідомий співрозмовник",
        "ja": "不明な相手",
        "de": "Unbekannte Person",
        "fr": "Interlocuteur inconnu",
        "zh": "未知对话方",
    },
    "ack_delivery_failed": {
        "en": "Acknowledgement delivery failed: {error}",
        "ru": "Не удалось доставить подтверждение: {error}",
        "uk": "Не вдалося доставити підтвердження: {error}",
        "ja": "確認メッセージを送信できませんでした: {error}",
        "de": "Bestätigung konnte nicht zugestellt werden: {error}",
        "fr": "Échec de l’envoi de l’accusé de réception : {error}",
        "zh": "确认消息发送失败：{error}",
    },
    "pending": {
        "en": "Pending",
        "ru": "Ожидает",
        "uk": "Очікує",
        "ja": "未対応",
        "de": "Offen",
        "fr": "En attente",
        "zh": "待处理",
    },
    "claimed": {
        "en": "Claimed",
        "ru": "Принято",
        "uk": "Прийнято",
        "ja": "対応中",
        "de": "Übernommen",
        "fr": "Pris en charge",
        "zh": "处理中",
    },
    "claim": {
        "en": "Claim",
        "ru": "Принять",
        "uk": "Прийняти",
        "ja": "引き受ける",
        "de": "Übernehmen",
        "fr": "Prendre en charge",
        "zh": "接手",
    },
    "resolve_keep_paused": {
        "en": "Resolve · keep paused",
        "ru": "Завершить · оставить выключенным",
        "uk": "Завершити · лишити вимкненим",
        "ja": "解決 · 停止を維持",
        "de": "Erledigen · pausiert lassen",
        "fr": "Résoudre · laisser en pause",
        "zh": "解决 · 保持暂停",
    },
    "resolve_resume": {
        "en": "Resolve · resume automation",
        "ru": "Завершить · возобновить автоматизацию",
        "uk": "Завершити · відновити автоматизацію",
        "ja": "解決 · 自動化を再開",
        "de": "Erledigen · Automatisierung fortsetzen",
        "fr": "Résoudre · reprendre l’automatisation",
        "zh": "解决 · 恢复自动化",
    },
    "dismiss_keep_paused": {
        "en": "Dismiss · keep paused",
        "ru": "Отклонить · оставить выключенным",
        "uk": "Відхилити · лишити вимкненим",
        "ja": "破棄 · 停止を維持",
        "de": "Verwerfen · pausiert lassen",
        "fr": "Ignorer · laisser en pause",
        "zh": "忽略 · 保持暂停",
    },
    "no_escalations": {
        "en": "No conversations are waiting for the owner.",
        "ru": "Нет диалогов, ожидающих владельца.",
        "uk": "Немає розмов, що очікують на власника.",
        "ja": "所有者の対応を待っている会話はありません。",
        "de": "Keine Unterhaltung wartet auf den Inhaber.",
        "fr": "Aucune conversation n’attend le propriétaire.",
        "zh": "没有等待所有者处理的对话。",
    },
    "reason_peer_requested_owner": {
        "en": "peer requested the owner",
        "ru": "собеседник запросил владельца",
        "uk": "співрозмовник запросив власника",
        "ja": "相手が所有者を希望",
        "de": "Person hat nach dem Inhaber gefragt",
        "fr": "l’interlocuteur a demandé le propriétaire",
        "zh": "对方请求联系所有者",
    },
    "reason_owner_only_information": {
        "en": "owner-only information",
        "ru": "нужны сведения владельца",
        "uk": "потрібні відомості власника",
        "ja": "所有者のみが回答可能",
        "de": "nur der Inhaber kann Auskunft geben",
        "fr": "informations réservées au propriétaire",
        "zh": "仅所有者可提供的信息",
    },
    "reason_other_explicit_request": {
        "en": "other explicit request",
        "ru": "другой явный запрос",
        "uk": "інший явний запит",
        "ja": "その他の明示的な依頼",
        "de": "andere ausdrückliche Anfrage",
        "fr": "autre demande explicite",
        "zh": "其他明确请求",
    },
    "reason_invalid_tool_arguments": {
        "en": "invalid tool arguments",
        "ru": "некорректные аргументы инструмента",
        "uk": "некоректні аргументи інструмента",
        "ja": "ツール引数が無効",
        "de": "ungültige Werkzeugargumente",
        "fr": "arguments d’outil invalides",
        "zh": "工具参数无效",
    },
    "test_hosted_web_search": {
        "en": "Test hosted web search",
        "ru": "Проверить встроенный веб-поиск",
        "uk": "Перевірити вбудований вебпошук",
        "ja": "ホスト型ウェブ検索をテスト",
        "de": "Integrierte Websuche testen",
        "fr": "Tester la recherche web hébergée",
        "zh": "测试托管网页搜索",
    },
    "web_search_available": {
        "en": "Available for {model}.",
        "ru": "Доступно для {model}.",
        "uk": "Доступно для {model}.",
        "ja": "{model} で利用できます。",
        "de": "Für {model} verfügbar.",
        "fr": "Disponible pour {model}.",
        "zh": "{model} 可用。",
    },
    "web_search_unavailable": {
        "en": "Not verified for {model}.",
        "ru": "Не подтверждено для {model}.",
        "uk": "Не підтверджено для {model}.",
        "ja": "{model} では確認できませんでした。",
        "de": "Für {model} nicht bestätigt.",
        "fr": "Non vérifié pour {model}.",
        "zh": "尚未确认 {model} 可用。",
    },
    "web_search_untested": {
        "en": "Not tested for {model}.",
        "ru": "Не проверено для {model}.",
        "uk": "Не перевірено для {model}.",
        "ja": "{model} では未テストです。",
        "de": "Für {model} nicht getestet.",
        "fr": "Non testé pour {model}.",
        "zh": "尚未测试 {model}。",
    },
    "subscription_help": _text(
        "Direct Plus/Pro OAuth with encrypted local credentials.",
        "Прямой OAuth Plus/Pro; учётные данные зашифрованы локально.",
        "Прямий OAuth Plus/Pro; облікові дані зашифровано локально.",
        "Plus/Pro OAuthを直接利用し、認証情報はローカルで暗号化します。",
        "直接使用 Plus/Pro OAuth，凭据在本地加密。",
        "Direktes Plus/Pro-OAuth; Zugangsdaten werden lokal verschlüsselt.",
        "OAuth Plus/Pro direct ; identifiants chiffrés localement.",
    ),
    "use_chatgpt": _text(
        "Use ChatGPT subscription",
        "Использовать подписку ChatGPT",
        "Використовувати підписку ChatGPT",
        "ChatGPTサブスクリプションを使う",
        "使用 ChatGPT 订阅",
        "ChatGPT-Abonnement verwenden",
        "Utiliser l’abonnement ChatGPT",
    ),
    "oauth_help": _text(
        "OpenAI redirects to localhost:1455. If it does not load, replace that prefix with {callback} and keep the complete query string.",
        "OpenAI перенаправляет на localhost:1455. Если страница не открылась, замените этот префикс на {callback}, сохранив всю строку запроса.",
        "OpenAI переспрямовує на localhost:1455. Якщо сторінка не відкрилася, замініть цей префікс на {callback}, зберігши весь рядок запиту.",
        "OpenAIはlocalhost:1455へリダイレクトします。開かない場合は、その部分だけを{callback}に置き換え、クエリ文字列全体を残してください。",
        "OpenAI 会重定向到 localhost:1455。若页面无法打开，只将该前缀替换为 {callback}，并保留完整查询字符串。",
        "OpenAI leitet zu localhost:1455 weiter. Falls die Seite nicht lädt, ersetze nur diesen Präfix durch {callback} und behalte die vollständige Abfragezeichenfolge.",
        "OpenAI redirige vers localhost:1455. Si la page ne charge pas, remplacez uniquement ce préfixe par {callback} en conservant toute la chaîne de requête.",
    ),
    "custom_provider_help": _text(
        "Connect a Responses API or Chat Completions provider. New providers default to Responses; the saved protocol stays pinned.",
        "Подключите провайдера Responses API или Chat Completions. Для новых выбран Responses; сохранённый протокол закрепляется.",
        "Підключіть провайдера Responses API або Chat Completions. Для нових вибрано Responses; збережений протокол закріплюється.",
        "Responses APIまたはChat Completionsプロバイダーを接続します。新規設定はResponsesが既定で、保存したプロトコルに固定されます。",
        "连接 Responses API 或 Chat Completions 提供商。新提供商默认使用 Responses，保存后协议固定。",
        "Verbinde einen Responses-API- oder Chat-Completions-Anbieter. Neue Anbieter verwenden standardmäßig Responses; das gespeicherte Protokoll bleibt fest.",
        "Connectez un fournisseur Responses API ou Chat Completions. Responses est présélectionné et le protocole enregistré reste fixe.",
    ),
    "provider_name": _text(
        "Provider name",
        "Название провайдера",
        "Назва провайдера",
        "プロバイダー名",
        "提供商名称",
        "Anbietername",
        "Nom du fournisseur",
    ),
    "local_model": _text(
        "Local model",
        "Локальная модель",
        "Локальна модель",
        "ローカルモデル",
        "本地模型",
        "Lokales Modell",
        "Modèle local",
    ),
    "api_base_url": _text(
        "API base URL",
        "Базовый URL API",
        "Базова URL-адреса API",
        "APIベースURL",
        "API 基础 URL",
        "API-Basis-URL",
        "URL de base de l’API",
    ),
    "api_key": _text("API key", "Ключ API", "Ключ API", "APIキー", "API 密钥", "API-Schlüssel", "Clé API"),
    "keep_saved_key": _text(
        "Leave empty to keep the saved key",
        "Оставьте пустым, чтобы сохранить ключ",
        "Залиште порожнім, щоб зберегти ключ",
        "保存済みキーを維持するには空欄",
        "留空以保留已保存的密钥",
        "Leer lassen, um den Schlüssel zu behalten",
        "Laisser vide pour conserver la clé",
    ),
    "key_optional": _text(
        "Optional for keyless endpoints",
        "Необязательно для конечных точек без ключа",
        "Необов’язково для точок без ключа",
        "キー不要のエンドポイントでは任意",
        "无密钥端点可不填",
        "Optional für Endpunkte ohne Schlüssel",
        "Facultatif pour les points d’accès sans clé",
    ),
    "api_protocol": _text(
        "API protocol",
        "Протокол API",
        "Протокол API",
        "APIプロトコル",
        "API 协议",
        "API-Protokoll",
        "Protocole API",
    ),
    "detection_model": _text(
        "Model used for detection",
        "Модель для проверки",
        "Модель для перевірки",
        "検出に使うモデル",
        "用于检测的模型",
        "Modell für die Erkennung",
        "Modèle utilisé pour la détection",
    ),
    "provider_capabilities": _text(
        "Provider capabilities",
        "Возможности провайдера",
        "Можливості провайдера",
        "プロバイダー機能",
        "提供商功能",
        "Anbieterfunktionen",
        "Capacités du fournisseur",
    ),
    "native_function_calls": _text(
        "Native function calls (required for automation)",
        "Нативные вызовы функций (обязательны)",
        "Нативні виклики функцій (обов’язкові)",
        "ネイティブ関数呼び出し（必須）",
        "原生函数调用（自动化必需）",
        "Native Funktionsaufrufe (erforderlich)",
        "Appels de fonction natifs (requis)",
    ),
    "strict_function_schemas": _text(
        "Strict function schemas",
        "Строгие схемы функций",
        "Суворі схеми функцій",
        "厳密な関数スキーマ",
        "严格函数架构",
        "Strikte Funktionsschemata",
        "Schémas de fonction stricts",
    ),
    "parallel_tool_control": _text(
        "parallel_tool_calls control",
        "Управление parallel_tool_calls",
        "Керування parallel_tool_calls",
        "parallel_tool_calls制御",
        "parallel_tool_calls 控制",
        "parallel_tool_calls-Steuerung",
        "Contrôle de parallel_tool_calls",
    ),
    "hosted_web_search": _text(
        "Hosted web search",
        "Встроенный веб-поиск",
        "Вбудований вебпошук",
        "ホスト型ウェブ検索",
        "托管网页搜索",
        "Integrierte Websuche",
        "Recherche web hébergée",
    ),
    "hosted_web_search_help": _text(
        "Responses API only; detection verifies search through reply.",
        "Только Responses API; проверяется весь путь до ответа.",
        "Лише Responses API; перевіряється весь шлях до відповіді.",
        "Responses APIのみ。検索から返信まで検証します。",
        "仅限 Responses API；检测会验证从搜索到回复的完整流程。",
        "Nur Responses API; der vollständige Ablauf wird geprüft.",
        "Responses API uniquement ; le flux complet est vérifié.",
    ),
    "remove_saved_key": _text(
        "Remove the saved API key",
        "Удалить сохранённый ключ API",
        "Видалити збережений ключ API",
        "保存済みAPIキーを削除",
        "删除已保存的 API 密钥",
        "Gespeicherten API-Schlüssel entfernen",
        "Supprimer la clé API enregistrée",
    ),
    "detect_api_support": _text(
        "Detect API support",
        "Определить поддержку API",
        "Визначити підтримку API",
        "API対応を検出",
        "检测 API 支持",
        "API-Unterstützung erkennen",
        "Détecter la prise en charge API",
    ),
    "update_use_provider": _text(
        "Update and use provider",
        "Обновить и использовать",
        "Оновити й використовувати",
        "更新して使用",
        "更新并使用提供商",
        "Aktualisieren und verwenden",
        "Mettre à jour et utiliser",
    ),
    "save_use_provider": _text(
        "Save and use provider",
        "Сохранить и использовать",
        "Зберегти й використовувати",
        "保存して使用",
        "保存并使用提供商",
        "Speichern und verwenden",
        "Enregistrer et utiliser",
    ),
    "use_provider": _text(
        "Use {name}",
        "Использовать {name}",
        "Використовувати {name}",
        "{name}を使う",
        "使用 {name}",
        "{name} verwenden",
        "Utiliser {name}",
    ),
    "remove_custom_provider": _text(
        "Remove custom provider",
        "Удалить провайдера",
        "Видалити провайдера",
        "カスタムプロバイダーを削除",
        "删除自定义提供商",
        "Eigenen Anbieter entfernen",
        "Supprimer le fournisseur personnalisé",
    ),
    "detection_help": _text(
        "Detection only preselects settings. Review and save explicitly; production never retries another protocol.",
        "Проверка лишь предварительно выбирает настройки. Проверьте и явно сохраните; другой протокол в работе не используется повторно.",
        "Перевірка лише попередньо вибирає налаштування. Перегляньте й явно збережіть; інший протокол у роботі не використовується повторно.",
        "検出は設定を事前選択するだけです。確認して明示的に保存してください。運用時に別プロトコルへ再試行しません。",
        "检测只会预选设置。请检查并明确保存；生产请求不会改用其他协议重试。",
        "Die Erkennung wählt nur vor. Prüfe und speichere ausdrücklich; im Betrieb wird kein anderes Protokoll versucht.",
        "La détection ne fait que présélectionner. Vérifiez et enregistrez ; aucun autre protocole n’est retenté en production.",
    ),
    "connecting": _text(
        "Connecting",
        "Подключение",
        "Підключення",
        "接続中",
        "正在连接",
        "Verbindung wird hergestellt",
        "Connexion en cours",
    ),
    "user_token": _text(
        "User token",
        "Токен пользователя",
        "Токен користувача",
        "ユーザートークン",
        "用户令牌",
        "Benutzertoken",
        "Jeton utilisateur",
    ),
    "paste_discord_token": _text(
        "Paste the Discord token",
        "Вставьте токен Discord",
        "Вставте токен Discord",
        "Discordトークンを貼り付け",
        "粘贴 Discord 令牌",
        "Discord-Token einfügen",
        "Collez le jeton Discord",
    ),
    "replace_reconnect": _text(
        "Replace token and reconnect",
        "Заменить токен и переподключиться",
        "Замінити токен і перепідключитися",
        "トークンを置換して再接続",
        "替换令牌并重新连接",
        "Token ersetzen und neu verbinden",
        "Remplacer le jeton et reconnecter",
    ),
    "disconnect_forget": _text(
        "Disconnect and forget token",
        "Отключиться и удалить токен",
        "Відключитися й видалити токен",
        "切断してトークンを削除",
        "断开连接并忘记令牌",
        "Trennen und Token vergessen",
        "Déconnecter et oublier le jeton",
    ),
    "captcha_requests": _text(
        "CAPTCHA requests",
        "Запросы CAPTCHA",
        "Запити CAPTCHA",
        "CAPTCHA要求",
        "CAPTCHA 请求",
        "CAPTCHA-Anfragen",
        "Demandes CAPTCHA",
    ),
    "pending_count": _text(
        "{count} pending",
        "Ожидают: {count}",
        "Очікують: {count}",
        "{count}件保留中",
        "{count} 个待处理",
        "{count} offen",
        "{count} en attente",
    ),
    "captcha_help": _text(
        "Solve the {service} challenge and paste its token below. About {seconds} seconds remain.",
        "Решите задачу {service} и вставьте токен ниже. Осталось около {seconds} с.",
        "Розв’яжіть задачу {service} і вставте токен нижче. Лишилося близько {seconds} с.",
        "{service}チャレンジを解き、トークンを貼り付けてください。残り約{seconds}秒です。",
        "完成 {service} 验证并在下方粘贴令牌。约剩 {seconds} 秒。",
        "Löse die {service}-Aufgabe und füge das Token unten ein. Noch etwa {seconds} Sekunden.",
        "Résolvez le défi {service} et collez le jeton ci-dessous. Environ {seconds} secondes restantes.",
    ),
    "site_key": _text(
        "Site key", "Ключ сайта", "Ключ сайту", "サイトキー", "站点密钥", "Site-Schlüssel", "Clé du site"
    ),
    "api_page": _text(
        "API page", "Страница API", "Сторінка API", "APIページ", "API 页面", "API-Seite", "Page API"
    ),
    "mode": _text("Mode", "Режим", "Режим", "モード", "模式", "Modus", "Mode"),
    "invisible": _text("invisible", "невидимый", "невидимий", "非表示", "隐形", "unsichtbar", "invisible"),
    "interactive": _text(
        "interactive", "интерактивный", "інтерактивний", "対話式", "交互式", "interaktiv", "interactif"
    ),
    "request_data": _text(
        "Request data",
        "Данные запроса",
        "Дані запиту",
        "リクエストデータ",
        "请求数据",
        "Anfragedaten",
        "Données de requête",
    ),
    "errors": _text("Errors", "Ошибки", "Помилки", "エラー", "错误", "Fehler", "Erreurs"),
    "captcha_solution": _text(
        "CAPTCHA solution token",
        "Токен решения CAPTCHA",
        "Токен розв’язання CAPTCHA",
        "CAPTCHA解決トークン",
        "CAPTCHA 解决令牌",
        "CAPTCHA-Lösungstoken",
        "Jeton de solution CAPTCHA",
    ),
    "submit_captcha": _text(
        "Submit CAPTCHA solution",
        "Отправить решение CAPTCHA",
        "Надіслати розв’язання CAPTCHA",
        "CAPTCHA解決を送信",
        "提交 CAPTCHA 解决方案",
        "CAPTCHA-Lösung senden",
        "Envoyer la solution CAPTCHA",
    ),
    "captcha_empty": _text(
        "Pending challenges appear here. Refresh after Discord reports a CAPTCHA.",
        "Ожидающие задачи появятся здесь. Обновите после сообщения Discord о CAPTCHA.",
        "Завдання з’являться тут. Оновіть після повідомлення Discord про CAPTCHA.",
        "保留中のチャレンジがここに表示されます。Discordの報告後に更新してください。",
        "待处理验证会显示在此。Discord 报告 CAPTCHA 后请刷新。",
        "Offene Aufgaben erscheinen hier. Nach einer Discord-CAPTCHA-Meldung aktualisieren.",
        "Les défis en attente apparaissent ici. Actualisez après un signalement CAPTCHA de Discord.",
    ),
    "personality_help": _text(
        "Infer reusable communication habits and synthetic examples from human-authored history.",
        "Выведите устойчивые привычки общения и синтетические примеры из сообщений человека.",
        "Виведіть сталі звички спілкування й синтетичні приклади з повідомлень людини.",
        "人が書いた履歴から再利用可能な会話習慣と合成例を推定します。",
        "从人工编写的历史中推断可复用的交流习惯和合成示例。",
        "Leite wiederverwendbare Kommunikationsmuster und synthetische Beispiele aus menschlich verfassten Nachrichten ab.",
        "Déduisez des habitudes de communication réutilisables et des exemples synthétiques depuis l’historique humain.",
    ),
    "recent_discord_messages": _text(
        "Recent Discord messages to inspect",
        "Недавние сообщения Discord",
        "Недавні повідомлення Discord",
        "確認する最近のDiscordメッセージ",
        "要检查的近期 Discord 消息",
        "Zu prüfende aktuelle Discord-Nachrichten",
        "Messages Discord récents à examiner",
    ),
    "load_infer_personality": _text(
        "Load history and infer personality",
        "Загрузить историю и вывести профиль",
        "Завантажити історію й вивести профіль",
        "履歴を読み込み人物像を推定",
        "加载历史并推断性格",
        "Verlauf laden und Persönlichkeit ableiten",
        "Charger l’historique et déduire la personnalité",
    ),
    "personality_requirements": _text(
        "Requires Discord and the active model; generated replies are excluded.",
        "Нужны Discord и активная модель; сгенерированные ответы исключаются.",
        "Потрібні Discord і активна модель; згенеровані відповіді виключено.",
        "Discordと有効なモデルが必要です。生成返信は除外されます。",
        "需要 Discord 和当前模型；自动生成回复不会纳入。",
        "Benötigt Discord und das aktive Modell; generierte Antworten sind ausgeschlossen.",
        "Nécessite Discord et le modèle actif ; les réponses générées sont exclues.",
    ),
    "infer_pasted_history": _text(
        "Infer from pasted message history",
        "Вывести из вставленной истории",
        "Вивести зі вставленої історії",
        "貼り付けた履歴から推定",
        "从粘贴的消息历史推断",
        "Aus eingefügtem Verlauf ableiten",
        "Déduire depuis un historique collé",
    ),
    "human_authored_history": _text(
        "Human-authored message history",
        "История сообщений человека",
        "Історія повідомлень людини",
        "人が書いたメッセージ履歴",
        "人工编写的消息历史",
        "Von Menschen verfasster Nachrichtenverlauf",
        "Historique de messages rédigés par une personne",
    ),
    "paste_history_placeholder": _text(
        "Paste at least 200 characters…",
        "Вставьте не менее 200 символов…",
        "Вставте щонайменше 200 символів…",
        "200文字以上貼り付け…",
        "粘贴至少 200 个字符…",
        "Mindestens 200 Zeichen einfügen…",
        "Collez au moins 200 caractères…",
    ),
    "infer_pasted_personality": _text(
        "Infer personality from pasted history",
        "Вывести профиль из истории",
        "Вивести профіль з історії",
        "貼り付けた履歴から人物像を推定",
        "从粘贴的历史推断性格",
        "Persönlichkeit aus Verlauf ableiten",
        "Déduire la personnalité de l’historique",
    ),
    "cached_personality_description": _text(
        "Cached personality description",
        "Сохранённое описание профиля",
        "Збережений опис профілю",
        "キャッシュ済み人物像",
        "已缓存的性格描述",
        "Gespeicherte Persönlichkeitsbeschreibung",
        "Description de personnalité en cache",
    ),
    "personality_placeholder": _text(
        "Infer a personality first, or write one manually…",
        "Сначала выведите профиль или заполните вручную…",
        "Спочатку виведіть профіль або заповніть вручну…",
        "先に人物像を推定するか手動で入力…",
        "先推断性格，或手动填写…",
        "Zuerst ableiten oder manuell schreiben…",
        "Déduisez d’abord un profil ou écrivez-le manuellement…",
    ),
    "last_source": _text(
        "Last source: {source}",
        "Последний источник: {source}",
        "Останнє джерело: {source}",
        "直近のソース：{source}",
        "最近来源：{source}",
        "Letzte Quelle: {source}",
        "Dernière source : {source}",
    ),
    "inferred_history": _text(
        "inferred history",
        "проанализированная история",
        "проаналізована історія",
        "推定済み履歴",
        "已分析历史",
        "analysierter Verlauf",
        "historique analysé",
    ),
    "save_edited_personality": _text(
        "Save edited personality",
        "Сохранить профиль",
        "Зберегти профіль",
        "編集した人物像を保存",
        "保存编辑后的性格",
        "Bearbeitete Persönlichkeit speichern",
        "Enregistrer la personnalité modifiée",
    ),
    "owner_timezone": _text(
        "Owner timezone",
        "Часовой пояс владельца",
        "Часовий пояс власника",
        "所有者のタイムゾーン",
        "所有者时区",
        "Zeitzone des Inhabers",
        "Fuseau horaire du propriétaire",
    ),
    "owner_timezone_help": _text(
        "Use an IANA name such as Europe/Berlin or Asia/Tokyo.",
        "Используйте имя IANA, например Europe/Berlin или Asia/Tokyo.",
        "Використовуйте назву IANA, наприклад Europe/Berlin або Asia/Tokyo.",
        "Europe/BerlinやAsia/TokyoなどのIANA名を使います。",
        "使用 Europe/Berlin 或 Asia/Tokyo 等 IANA 名称。",
        "Verwende einen IANA-Namen wie Europe/Berlin oder Asia/Tokyo.",
        "Utilisez un nom IANA comme Europe/Berlin ou Asia/Tokyo.",
    ),
    "silent_replies_help": _text(
        "Uses Discord suppress-notifications without changing visible text.",
        "Использует подавление уведомлений Discord без изменения текста.",
        "Використовує приглушення сповіщень Discord без зміни тексту.",
        "表示文を変えずDiscord通知を抑制します。",
        "使用 Discord 抑制通知选项，不改变可见文本。",
        "Unterdrückt Discord-Benachrichtigungen ohne sichtbaren Text zu ändern.",
        "Supprime les notifications Discord sans modifier le texte visible.",
    ),
    "robot_prefix_help": _text(
        "Adds a visible robot emoji so assistant messages are distinguishable.",
        "Добавляет видимый эмодзи робота, чтобы отличать ответы ассистента.",
        "Додає видимий емодзі робота, щоб відрізняти відповіді асистента.",
        "アシスタント返信を区別できるようロボット絵文字を付けます。",
        "添加可见机器人表情以区分助手消息。",
        "Fügt ein sichtbares Roboter-Emoji zur Unterscheidung hinzu.",
        "Ajoute un émoji robot visible pour distinguer les messages.",
    ),
    "enrollment_policy": _text(
        "Enrollment policy",
        "Политика подключения",
        "Політика підключення",
        "登録ポリシー",
        "加入策略",
        "Teilnahmeregel",
        "Politique d’inscription",
    ),
    "opt_in": _text(
        "Opt in — automate new conversations",
        "Включать новые диалоги",
        "Вмикати нові розмови",
        "オプトイン—新規会話を自動化",
        "选择加入——自动处理新对话",
        "Opt-in — neue Unterhaltungen automatisieren",
        "Inscription — automatiser les nouvelles conversations",
    ),
    "opt_out": _text(
        "Opt out — require manual enablement",
        "Не включать без ручного разрешения",
        "Не вмикати без ручного дозволу",
        "オプトアウト—手動で有効化",
        "选择退出——需要手动启用",
        "Opt-out — manuelle Aktivierung nötig",
        "Désinscription — activation manuelle requise",
    ),
    "enrollment_help": _text(
        "Applies when a DM is first observed; existing conversations keep their setting.",
        "Применяется при первом появлении диалога; существующие настройки сохраняются.",
        "Застосовується при першій появі розмови; наявні налаштування зберігаються.",
        "DMを初めて検出した時に適用し、既存会話の設定は維持します。",
        "首次发现私聊时应用；现有对话保留各自设置。",
        "Gilt beim ersten Erkennen einer DM; bestehende Einstellungen bleiben erhalten.",
        "S’applique à la première détection d’un MP ; les réglages existants sont conservés.",
    ),
    "custom_not_configured": _text(
        "Custom API (not configured)",
        "Свой API (не настроен)",
        "Власний API (не налаштовано)",
        "カスタムAPI（未設定）",
        "自定义 API（未配置）",
        "Eigene API (nicht konfiguriert)",
        "API personnalisée (non configurée)",
    ),
    "low": _text("Low", "Низкое", "Низьке", "低", "低", "Niedrig", "Faible"),
    "medium": _text("Medium", "Среднее", "Середнє", "中", "中", "Mittel", "Moyen"),
    "high": _text("High", "Высокое", "Високе", "高", "高", "Hoch", "Élevé"),
    "token_budget_help": _text(
        "Subscription uses a best-effort length instruction; custom APIs receive a hard token limit.",
        "Для подписки это ориентир длины; свой API получает жёсткий лимит токенов.",
        "Для підписки це орієнтир довжини; власний API отримує жорсткий ліміт токенів.",
        "サブスクリプションでは長さの目安、カスタムAPIでは厳密なトークン上限です。",
        "订阅使用尽力长度指令；自定义 API 接收硬性令牌限制。",
        "Beim Abonnement ist es eine Längenvorgabe; eigene APIs erhalten ein hartes Tokenlimit.",
        "L’abonnement reçoit une consigne de longueur ; les API personnalisées une limite stricte.",
    ),
    "allow_message_sequences": _text(
        "Allow message sequences",
        "Разрешить серии сообщений",
        "Дозволити серії повідомлень",
        "メッセージ列を許可",
        "允许消息序列",
        "Nachrichtenfolgen erlauben",
        "Autoriser les séquences de messages",
    ),
    "message_sequences_help": _text(
        "The model chooses natural boundaries and may still send one message.",
        "Модель выбирает естественные границы и может отправить одно сообщение.",
        "Модель обирає природні межі й може надіслати одне повідомлення.",
        "モデルが自然な区切りを選び、1件だけ送ることもできます。",
        "模型选择自然边界，也可以只发送一条。",
        "Das Modell wählt natürliche Grenzen und kann bei einer Nachricht bleiben.",
        "Le modèle choisit des limites naturelles et peut conserver un seul message.",
    ),
    "maximum_messages": _text(
        "Maximum messages",
        "Максимум сообщений",
        "Максимум повідомлень",
        "最大メッセージ数",
        "最大消息数",
        "Maximale Nachrichten",
        "Nombre maximal de messages",
    ),
    "minimum_gap": _text(
        "Minimum gap (seconds)",
        "Минимальный интервал (с)",
        "Мінімальний інтервал (с)",
        "最小間隔（秒）",
        "最小间隔（秒）",
        "Minimaler Abstand (Sekunden)",
        "Intervalle minimal (secondes)",
    ),
    "maximum_gap": _text(
        "Maximum gap (seconds)",
        "Максимальный интервал (с)",
        "Максимальний інтервал (с)",
        "最大間隔（秒）",
        "最大间隔（秒）",
        "Maximaler Abstand (Sekunden)",
        "Intervalle maximal (secondes)",
    ),
    "debounce": _text(
        "Debounce (seconds)",
        "Задержка объединения (с)",
        "Затримка об’єднання (с)",
        "デバウンス（秒）",
        "防抖（秒）",
        "Entprellzeit (Sekunden)",
        "Temporisation (secondes)",
    ),
    "minimum_delay": _text(
        "Minimum delay",
        "Минимальная задержка",
        "Мінімальна затримка",
        "最小遅延",
        "最小延迟",
        "Minimale Verzögerung",
        "Délai minimal",
    ),
    "maximum_delay": _text(
        "Maximum delay",
        "Максимальная задержка",
        "Максимальна затримка",
        "最大遅延",
        "最大延迟",
        "Maximale Verzögerung",
        "Délai maximal",
    ),
    "quiet_window_help": _text(
        "A manual outgoing message cancels pending work and starts a random quiet period.",
        "Ручное сообщение отменяет работу и запускает случайную паузу.",
        "Ручне повідомлення скасовує роботу й запускає випадкову паузу.",
        "手動送信は保留処理を中止し、ランダムな休止時間を開始します。",
        "手动发出消息会取消待处理工作并开始随机静默期。",
        "Eine manuelle Nachricht bricht offene Arbeit ab und startet eine zufällige Ruhezeit.",
        "Un message manuel annule le travail en attente et lance une pause aléatoire.",
    ),
    "minimum_quiet_minutes": _text(
        "Minimum quiet minutes",
        "Минимум минут паузы",
        "Мінімум хвилин паузи",
        "最小休止時間（分）",
        "最短静默分钟",
        "Minimale Ruheminuten",
        "Minutes de pause minimales",
    ),
    "maximum_quiet_minutes": _text(
        "Maximum quiet minutes",
        "Максимум минут паузы",
        "Максимум хвилин паузи",
        "最大休止時間（分）",
        "最长静默分钟",
        "Maximale Ruheminuten",
        "Minutes de pause maximales",
    ),
    "minimum_typing_speed": _text(
        "Minimum characters/s",
        "Минимум символов/с",
        "Мінімум символів/с",
        "最小文字数/秒",
        "最小字符/秒",
        "Minimale Zeichen/s",
        "Caractères/s minimum",
    ),
    "maximum_typing_speed": _text(
        "Maximum characters/s",
        "Максимум символов/с",
        "Максимум символів/с",
        "最大文字数/秒",
        "最大字符/秒",
        "Maximale Zeichen/s",
        "Caractères/s maximum",
    ),
    "history_messages": _text(
        "History messages",
        "Сообщений в истории",
        "Повідомлень в історії",
        "履歴メッセージ数",
        "历史消息数",
        "Verlaufsnachrichten",
        "Messages d’historique",
    ),
    "owner_details_placeholder": _text(
        "Name, location, work, interests, relationships, preferences, plans, and other useful facts…",
        "Имя, место, работа, интересы, отношения, предпочтения, планы и другие полезные факты…",
        "Ім’я, місце, робота, інтереси, стосунки, уподобання, плани та інші корисні факти…",
        "名前、場所、仕事、関心、人間関係、好み、予定など…",
        "姓名、地点、工作、兴趣、关系、偏好、计划及其他有用事实…",
        "Name, Ort, Arbeit, Interessen, Beziehungen, Vorlieben, Pläne und weitere nützliche Fakten…",
        "Nom, lieu, travail, centres d’intérêt, relations, préférences, projets et autres faits utiles…",
    ),
    "owner_details_help": _text(
        "Authoritative context used only when relevant; unrelated private details must not be volunteered.",
        "Авторитетный контекст только по делу; посторонние личные сведения не сообщаются.",
        "Авторитетний контекст лише доречно; сторонні особисті відомості не повідомляються.",
        "関係する場合だけ使う確定情報で、無関係な個人情報は明かしません。",
        "仅在相关时使用的权威背景；不会主动透露无关隐私。",
        "Maßgeblicher Kontext nur bei Relevanz; fremde private Details werden nicht angeboten.",
        "Contexte faisant autorité, utilisé seulement si pertinent ; aucun détail privé sans rapport n’est divulgué.",
    ),
    "calls_count": _text(
        "{count} calls",
        "Вызовов: {count}",
        "Викликів: {count}",
        "{count}回",
        "{count} 次调用",
        "{count} Aufrufe",
        "{count} appels",
    ),
    "usage_help": _text(
        "Provider-reported counters only; prompts and generated text are not copied here.",
        "Только счётчики провайдера; промпты и ответы сюда не копируются.",
        "Лише лічильники провайдера; промпти й відповіді сюди не копіюються.",
        "プロバイダー報告のカウンターのみ。プロンプトや生成文は保存しません。",
        "仅显示提供商报告的计数；不会复制提示词和生成文本。",
        "Nur vom Anbieter gemeldete Zähler; Prompts und Texte werden nicht kopiert.",
        "Compteurs déclarés par le fournisseur uniquement ; prompts et textes ne sont pas copiés.",
    ),
    "all_time_usage": _text(
        "All-time usage summary",
        "Сводка за всё время",
        "Зведення за весь час",
        "全期間の使用概要",
        "全部时间使用摘要",
        "Nutzungsübersicht für alle Zeiten",
        "Résumé d’utilisation global",
    ),
    "total_tokens": _text(
        "Total tokens",
        "Всего токенов",
        "Усього токенів",
        "合計トークン",
        "总令牌",
        "Token gesamt",
        "Total des jetons",
    ),
    "input": _text("Input", "Ввод", "Вхід", "入力", "输入", "Eingabe", "Entrée"),
    "cached_input": _text(
        "Cached input",
        "Кэшированный ввод",
        "Кешований вхід",
        "キャッシュ入力",
        "缓存输入",
        "Zwischengespeicherte Eingabe",
        "Entrée en cache",
    ),
    "percent_of_input": _text(
        "{percent}% of input",
        "{percent}% ввода",
        "{percent}% входу",
        "入力の{percent}%",
        "占输入的 {percent}%",
        "{percent}% der Eingabe",
        "{percent}% de l’entrée",
    ),
    "output": _text("Output", "Вывод", "Вивід", "出力", "输出", "Ausgabe", "Sortie"),
    "reasoning_output": _text(
        "Reasoning · of output",
        "Рассуждение · из вывода",
        "Міркування · з виводу",
        "推論・出力内",
        "推理 · 输出的一部分",
        "Schlussfolgern · der Ausgabe",
        "Raisonnement · de la sortie",
    ),
    "average_per_call": _text(
        "Average / call",
        "Среднее / вызов",
        "Середнє / виклик",
        "平均／回",
        "平均 / 调用",
        "Durchschnitt / Aufruf",
        "Moyenne / appel",
    ),
    "time_windows": _text(
        "Time windows", "Периоды", "Періоди", "期間", "时间窗口", "Zeitfenster", "Périodes"
    ),
    "window": _text("Window", "Период", "Період", "期間", "窗口", "Fenster", "Période"),
    "calls": _text("Calls", "Вызовы", "Виклики", "呼び出し", "调用", "Aufrufe", "Appels"),
    "total": _text("Total", "Всего", "Усього", "合計", "总计", "Gesamt", "Total"),
    "by_model": _text(
        "By model", "По моделям", "За моделями", "モデル別", "按模型", "Nach Modell", "Par modèle"
    ),
    "no_completed_calls": _text(
        "No completed calls yet.",
        "Завершённых вызовов пока нет.",
        "Завершених викликів ще немає.",
        "完了した呼び出しはまだありません。",
        "尚无已完成调用。",
        "Noch keine abgeschlossenen Aufrufe.",
        "Aucun appel terminé.",
    ),
    "by_operation": _text(
        "By operation", "По операциям", "За операціями", "操作別", "按操作", "Nach Vorgang", "Par opération"
    ),
    "operation": _text("Operation", "Операция", "Операція", "操作", "操作", "Vorgang", "Opération"),
    "recent_calls": _text(
        "Recent calls · {count}",
        "Последние вызовы · {count}",
        "Останні виклики · {count}",
        "最近の呼び出し・{count}",
        "最近调用 · {count}",
        "Letzte Aufrufe · {count}",
        "Appels récents · {count}",
    ),
    "time": _text("Time", "Время", "Час", "時刻", "时间", "Zeit", "Heure"),
    "no_usage": _text(
        "No usage has been recorded yet.",
        "Использование пока не записано.",
        "Використання ще не записано.",
        "使用状況はまだ記録されていません。",
        "尚未记录使用情况。",
        "Noch keine Nutzung aufgezeichnet.",
        "Aucune utilisation enregistrée.",
    ),
    "purpose_dm_reply": _text(
        "DM reply", "Ответ в ЛС", "Відповідь у ПП", "DM返信", "私聊回复", "DM-Antwort", "Réponse MP"
    ),
    "purpose_dm_reply_tool_continuation": _text(
        "DM tool continuation",
        "Продолжение инструмента ЛС",
        "Продовження інструмента ПП",
        "DMツール継続",
        "私聊工具继续",
        "DM-Werkzeugfortsetzung",
        "Suite d’outil MP",
    ),
    "purpose_personality_inference": _text(
        "Personality inference",
        "Вывод профиля",
        "Виведення профілю",
        "人物像推定",
        "性格推断",
        "Persönlichkeitsableitung",
        "Déduction de personnalité",
    ),
    "purpose_web_search_capability_probe": _text(
        "Web search probe",
        "Проверка веб-поиска",
        "Перевірка вебпошуку",
        "ウェブ検索テスト",
        "网页搜索测试",
        "Websuchtest",
        "Test de recherche web",
    ),
    "purpose_conversation": _text(
        "Conversation", "Разговор", "Розмова", "会話", "对话", "Unterhaltung", "Conversation"
    ),
    "known_count": _text(
        "{count} known",
        "Известно: {count}",
        "Відомо: {count}",
        "{count}件",
        "已知 {count} 个",
        "{count} bekannt",
        "{count} connue(s)",
    ),
    "conversations_help": _text(
        "Each conversation has independent automation. Manual activity starts a quiet window; a forced reply still stops before a manual send.",
        "У каждого диалога своя автоматизация. Ручная активность запускает паузу; принудительный ответ всё равно остановится перед ручной отправкой.",
        "Кожна розмова має власну автоматизацію. Ручна активність запускає паузу; примусова відповідь усе одно зупиниться перед ручним надсиланням.",
        "会話ごとに自動化を管理します。手動操作で休止し、強制返信も手動送信前に停止します。",
        "每个对话独立管理自动化。手动活动会启动静默期；强制回复也会在手动发送前停止。",
        "Jede Unterhaltung hat eigene Automatisierung. Manuelle Aktivität startet eine Ruhezeit; auch erzwungene Antworten stoppen vor manuellem Senden.",
        "Chaque conversation gère son automatisation. Une activité manuelle lance une pause ; même une réponse forcée s’arrête avant un envoi manuel.",
    ),
    "channel": _text(
        "Channel {id}", "Канал {id}", "Канал {id}", "チャンネル{id}", "频道 {id}", "Kanal {id}", "Canal {id}"
    ),
    "automation_off": _text(
        "Automation off",
        "Автоматизация выключена",
        "Автоматизацію вимкнено",
        "自動化オフ",
        "自动化关闭",
        "Automatisierung aus",
        "Automatisation arrêtée",
    ),
    "human_active": _text(
        "Human active · {minutes} min",
        "Человек активен · {minutes} мин",
        "Людина активна · {minutes} хв",
        "手動操作中・{minutes}分",
        "人工活动 · {minutes} 分钟",
        "Mensch aktiv · {minutes} Min.",
        "Humain actif · {minutes} min",
    ),
    "automatic": _text(
        "Automatic", "Автоматически", "Автоматично", "自動", "自动", "Automatisch", "Automatique"
    ),
    "resume_now": _text(
        "Resume now",
        "Возобновить сейчас",
        "Відновити зараз",
        "今すぐ再開",
        "立即恢复",
        "Jetzt fortsetzen",
        "Reprendre maintenant",
    ),
    "no_dms": _text(
        "No DMs observed yet.",
        "Личных сообщений пока нет.",
        "Приватних повідомлень ще немає.",
        "DMはまだありません。",
        "尚未发现私聊。",
        "Noch keine DMs beobachtet.",
        "Aucun MP observé.",
    ),
    "matching_rows": _text(
        "{count} matching rows",
        "Совпадений: {count}",
        "Збігів: {count}",
        "一致行：{count}",
        "{count} 行匹配",
        "{count} passende Zeilen",
        "{count} lignes correspondantes",
    ),
    "database_help": _text(
        "Browse local SQLite tables. Encrypted values are redacted; configuration is read-only.",
        "Просматривайте локальные таблицы SQLite. Зашифрованные значения скрыты; конфигурация доступна только для чтения.",
        "Переглядайте локальні таблиці SQLite. Зашифровані значення приховано; конфігурація лише для читання.",
        "ローカルSQLiteテーブルを参照します。暗号化値は伏せ、設定は読み取り専用です。",
        "浏览本地 SQLite 表。加密值会被隐藏；配置只读。",
        "Lokale SQLite-Tabellen durchsuchen. Verschlüsselte Werte sind verborgen; Konfiguration ist schreibgeschützt.",
        "Parcourez les tables SQLite locales. Les valeurs chiffrées sont masquées ; la configuration est en lecture seule.",
    ),
    "database_tables": _text(
        "Database tables",
        "Таблицы базы данных",
        "Таблиці бази даних",
        "データベーステーブル",
        "数据库表",
        "Datenbanktabellen",
        "Tables de base de données",
    ),
    "search_table": _text(
        "Search {table}",
        "Поиск в {table}",
        "Пошук у {table}",
        "{table}を検索",
        "搜索 {table}",
        "{table} durchsuchen",
        "Rechercher dans {table}",
    ),
    "search_columns": _text(
        "Search visible columns…",
        "Поиск по видимым столбцам…",
        "Пошук у видимих стовпцях…",
        "表示列を検索…",
        "搜索可见列…",
        "Sichtbare Spalten durchsuchen…",
        "Rechercher les colonnes visibles…",
    ),
    "no_matching_rows": _text(
        "No rows match this view.",
        "Нет подходящих строк.",
        "Немає відповідних рядків.",
        "一致する行はありません。",
        "没有匹配的行。",
        "Keine passenden Zeilen.",
        "Aucune ligne correspondante.",
    ),
    "page_of": _text(
        "Page {page} of {pages}",
        "Страница {page} из {pages}",
        "Сторінка {page} з {pages}",
        "{pages}ページ中{page}",
        "第 {page} 页，共 {pages} 页",
        "Seite {page} von {pages}",
        "Page {page} sur {pages}",
    ),
    "delete_one_row": _text(
        "Delete one row",
        "Удалить одну строку",
        "Видалити один рядок",
        "1行削除",
        "删除一行",
        "Eine Zeile löschen",
        "Supprimer une ligne",
    ),
    "key_value": _text(
        "{column} value",
        "Значение {column}",
        "Значення {column}",
        "{column}の値",
        "{column} 值",
        "{column}-Wert",
        "Valeur {column}",
    ),
    "confirm_delete": _text(
        "I understand this permanently deletes the selected row",
        "Я понимаю, что выбранная строка будет удалена навсегда",
        "Я розумію, що вибраний рядок буде видалено назавжди",
        "選択行が完全に削除されることを理解しました",
        "我了解这会永久删除所选行",
        "Ich verstehe, dass die Zeile dauerhaft gelöscht wird",
        "Je comprends que cette ligne sera supprimée définitivement",
    ),
    "delete_row": _text(
        "Delete row",
        "Удалить строку",
        "Видалити рядок",
        "行を削除",
        "删除行",
        "Zeile löschen",
        "Supprimer la ligne",
    ),
    "footer": _text(
        "Diskovod · Discord DM assistant",
        "Diskovod · Ассистент личных сообщений Discord",
        "Diskovod · Асистент приватних повідомлень Discord",
        "Diskovod・Discord DMアシスタント",
        "Diskovod · Discord 私聊助手",
        "Diskovod · Discord-DM-Assistent",
        "Diskovod · Assistant de MP Discord",
    ),
    "last_24_hours": _text(
        "Last 24 hours",
        "Последние 24 часа",
        "Останні 24 години",
        "過去24時間",
        "过去 24 小时",
        "Letzte 24 Stunden",
        "Dernières 24 heures",
    ),
    "last_7_days": _text(
        "Last 7 days",
        "Последние 7 дней",
        "Останні 7 днів",
        "過去7日間",
        "过去 7 天",
        "Letzte 7 Tage",
        "7 derniers jours",
    ),
    "last_30_days": _text(
        "Last 30 days",
        "Последние 30 дней",
        "Останні 30 днів",
        "過去30日間",
        "过去 30 天",
        "Letzte 30 Tage",
        "30 derniers jours",
    ),
    "all_time": _text(
        "All time", "Всё время", "Увесь час", "全期間", "全部时间", "Gesamter Zeitraum", "Toute la période"
    ),
    "table_config": _text(
        "Configuration", "Конфигурация", "Конфігурація", "設定", "配置", "Konfiguration", "Configuration"
    ),
    "table_conversations": _text(
        "Conversations", "Диалоги", "Розмови", "会話", "对话", "Unterhaltungen", "Conversations"
    ),
    "table_messages": _text(
        "Messages", "Сообщения", "Повідомлення", "メッセージ", "消息", "Nachrichten", "Messages"
    ),
    "table_assistant_reactions": _text(
        "Assistant reactions",
        "Реакции ассистента",
        "Реакції асистента",
        "アシスタントのリアクション",
        "助手回应表情",
        "Assistentenreaktionen",
        "Réactions de l’assistant",
    ),
    "table_conversation_escalations": _text(
        "Owner escalations",
        "Обращения к владельцу",
        "Звернення до власника",
        "所有者へのエスカレーション",
        "转交所有者",
        "Weiterleitungen an den Inhaber",
        "Transferts au propriétaire",
    ),
    "table_chatgpt_usage": _text(
        "Model usage",
        "Использование модели",
        "Використання моделі",
        "モデル使用量",
        "模型使用情况",
        "Modellnutzung",
        "Utilisation du modèle",
    ),
    "table_bot_nonces": _text(
        "Pending nonces",
        "Ожидающие nonce",
        "Очікувані nonce",
        "保留中nonce",
        "待处理随机数",
        "Ausstehende Nonces",
        "Nonces en attente",
    ),
    "table_bot_message_ids": _text(
        "Assistant message markers",
        "Маркеры сообщений ассистента",
        "Маркери повідомлень асистента",
        "アシスタントメッセージ印",
        "助手消息标记",
        "Assistenten-Nachrichtenmarker",
        "Marqueurs des messages de l’assistant",
    ),
    "chatgpt_connected": _text(
        "ChatGPT connected and selected",
        "ChatGPT подключён и выбран",
        "ChatGPT підключено й вибрано",
        "ChatGPTに接続して選択しました",
        "ChatGPT 已连接并选中",
        "ChatGPT verbunden und ausgewählt",
        "ChatGPT connecté et sélectionné",
    ),
    "chatgpt_disconnected": _text(
        "ChatGPT disconnected",
        "ChatGPT отключён",
        "ChatGPT відключено",
        "ChatGPTから切断しました",
        "ChatGPT 已断开",
        "ChatGPT getrennt",
        "ChatGPT déconnecté",
    ),
    "web_search_probe_failed": _text(
        "Web search probe failed: {detail}",
        "Проверка веб-поиска не удалась: {detail}",
        "Перевірка вебпошуку не вдалася: {detail}",
        "ウェブ検索テストに失敗しました：{detail}",
        "网页搜索测试失败：{detail}",
        "Websuchtest fehlgeschlagen: {detail}",
        "Échec du test de recherche web : {detail}",
    ),
    "web_search_probe_available": _text(
        "Hosted web search is available for the selected subscription model",
        "Встроенный веб-поиск доступен для выбранной модели подписки",
        "Вбудований вебпошук доступний для вибраної моделі підписки",
        "選択したサブスクリプションモデルでホスト型ウェブ検索を利用できます",
        "所选订阅模型支持托管网页搜索",
        "Gehostete Websuche ist für das ausgewählte Abonnementmodell verfügbar",
        "La recherche web hébergée est disponible pour le modèle d’abonnement sélectionné",
    ),
    "web_search_probe_unavailable": _text(
        "The selected subscription model did not complete the hosted search test",
        "Выбранная модель подписки не прошла проверку встроенного веб-поиска",
        "Вибрана модель підписки не пройшла перевірку вбудованого вебпошуку",
        "選択したサブスクリプションモデルはホスト型検索テストを完了できませんでした",
        "所选订阅模型未能完成托管搜索测试",
        "Das ausgewählte Abonnementmodell hat den Test der gehosteten Suche nicht abgeschlossen",
        "Le modèle d’abonnement sélectionné n’a pas terminé le test de recherche hébergée",
    ),
    "provider_name_invalid": _text(
        "Provider name must contain between 1 and 80 characters",
        "Название провайдера должно содержать от 1 до 80 символов",
        "Назва провайдера має містити від 1 до 80 символів",
        "プロバイダー名は1〜80文字にしてください",
        "提供商名称须为 1 至 80 个字符",
        "Der Anbietername muss 1 bis 80 Zeichen lang sein",
        "Le nom du fournisseur doit contenir entre 1 et 80 caractères",
    ),
    "unknown_api_protocol": _text(
        "Unknown API protocol",
        "Неизвестный протокол API",
        "Невідомий протокол API",
        "不明なAPIプロトコルです",
        "未知 API 协议",
        "Unbekanntes API-Protokoll",
        "Protocole d’API inconnu",
    ),
    "disable_automation_for_provider": _text(
        "Disable automation before selecting a provider without native function calls",
        "Отключите автоматизацию перед выбором провайдера без нативных вызовов функций",
        "Вимкніть автоматизацію перед вибором провайдера без нативних викликів функцій",
        "ネイティブ関数呼び出しのないプロバイダーを選ぶ前に自動化を無効にしてください",
        "选择不支持原生函数调用的提供商前请关闭自动化",
        "Deaktivieren Sie die Automatisierung, bevor Sie einen Anbieter ohne native Funktionsaufrufe auswählen",
        "Désactivez l’automatisation avant de choisir un fournisseur sans appels de fonction natifs",
    ),
    "provider_saved": _text(
        "{name} saved and selected",
        "{name} сохранён и выбран",
        "{name} збережено й вибрано",
        "{name}を保存して選択しました",
        "已保存并选中 {name}",
        "{name} gespeichert und ausgewählt",
        "{name} enregistré et sélectionné",
    ),
    "detection_model_required": _text(
        "Enter a model name for API detection",
        "Укажите модель для определения возможностей API",
        "Укажіть модель для визначення можливостей API",
        "API検出に使うモデル名を入力してください",
        "请输入用于 API 检测的模型名称",
        "Geben Sie einen Modellnamen für die API-Erkennung ein",
        "Saisissez un nom de modèle pour la détection de l’API",
    ),
    "provider_detection_result": _text(
        "Detected {protocol}; {native}; {web}. Review the preselected settings, then save explicitly.",
        "Обнаружено: {protocol}; {native}; {web}. Проверьте предварительно выбранные настройки и явно сохраните их.",
        "Виявлено: {protocol}; {native}; {web}. Перевірте попередньо вибрані налаштування та явно збережіть їх.",
        "検出結果：{protocol}、{native}、{web}。事前選択された設定を確認し、明示的に保存してください。",
        "检测到：{protocol}；{native}；{web}。请检查预选设置，然后明确保存。",
        "Erkannt: {protocol}; {native}; {web}. Prüfen Sie die vorausgewählten Einstellungen und speichern Sie sie ausdrücklich.",
        "Détection : {protocol} ; {native} ; {web}. Vérifiez les réglages présélectionnés, puis enregistrez-les explicitement.",
    ),
    "native_calls_available": _text(
        "native function calls available",
        "нативные вызовы функций доступны",
        "нативні виклики функцій доступні",
        "ネイティブ関数呼び出し利用可能",
        "原生函数调用可用",
        "native Funktionsaufrufe verfügbar",
        "appels de fonction natifs disponibles",
    ),
    "native_calls_unavailable": _text(
        "native function calls unavailable",
        "нативные вызовы функций недоступны",
        "нативні виклики функцій недоступні",
        "ネイティブ関数呼び出し利用不可",
        "原生函数调用不可用",
        "native Funktionsaufrufe nicht verfügbar",
        "appels de fonction natifs indisponibles",
    ),
    "hosted_search_available": _text(
        "hosted web search available",
        "встроенный веб-поиск доступен",
        "вбудований вебпошук доступний",
        "ホスト型ウェブ検索利用可能",
        "托管网页搜索可用",
        "gehostete Websuche verfügbar",
        "recherche web hébergée disponible",
    ),
    "hosted_search_unavailable": _text(
        "hosted web search unavailable",
        "встроенный веб-поиск недоступен",
        "вбудований вебпошук недоступний",
        "ホスト型ウェブ検索利用不可",
        "托管网页搜索不可用",
        "gehostete Websuche nicht verfügbar",
        "recherche web hébergée indisponible",
    ),
    "custom_provider_removed": _text(
        "Custom provider removed",
        "Пользовательский провайдер удалён",
        "Користувацького провайдера видалено",
        "カスタムプロバイダーを削除しました",
        "自定义提供商已移除",
        "Benutzerdefinierter Anbieter entfernt",
        "Fournisseur personnalisé supprimé",
    ),
    "unknown_model_provider": _text(
        "Unknown model provider",
        "Неизвестный провайдер модели",
        "Невідомий провайдер моделі",
        "不明なモデルプロバイダーです",
        "未知模型提供商",
        "Unbekannter Modellanbieter",
        "Fournisseur de modèle inconnu",
    ),
    "connect_chatgpt_first": _text(
        "Connect ChatGPT before selecting it",
        "Подключите ChatGPT перед выбором",
        "Підключіть ChatGPT перед вибором",
        "選択する前にChatGPTへ接続してください",
        "选择 ChatGPT 前请先连接",
        "Verbinden Sie ChatGPT, bevor Sie es auswählen",
        "Connectez ChatGPT avant de le sélectionner",
    ),
    "configure_custom_provider_first": _text(
        "Configure a custom provider before selecting it",
        "Настройте пользовательский провайдер перед выбором",
        "Налаштуйте користувацького провайдера перед вибором",
        "選択する前にカスタムプロバイダーを設定してください",
        "选择自定义提供商前请先配置",
        "Konfigurieren Sie einen benutzerdefinierten Anbieter, bevor Sie ihn auswählen",
        "Configurez un fournisseur personnalisé avant de le sélectionner",
    ),
    "detect_native_calls_before_select": _text(
        "Disable automation or detect native function-call support before selecting it",
        "Отключите автоматизацию или определите поддержку нативных вызовов функций перед выбором",
        "Вимкніть автоматизацію або визначте підтримку нативних викликів функцій перед вибором",
        "選択する前に自動化を無効にするか、ネイティブ関数呼び出し対応を検出してください",
        "选择前请关闭自动化或检测原生函数调用支持",
        "Deaktivieren Sie die Automatisierung oder erkennen Sie native Funktionsaufrufe vor der Auswahl",
        "Désactivez l’automatisation ou détectez la prise en charge des appels de fonction natifs avant la sélection",
    ),
    "provider_selected": _text(
        "{name} selected",
        "Выбран провайдер {name}",
        "Вибрано провайдера {name}",
        "{name}を選択しました",
        "已选择 {name}",
        "{name} ausgewählt",
        "{name} sélectionné",
    ),
    "discord_token_incomplete": _text(
        "Discord token appears to be incomplete",
        "Токен Discord выглядит неполным",
        "Токен Discord виглядає неповним",
        "Discordトークンが不完全です",
        "Discord 令牌似乎不完整",
        "Das Discord-Token scheint unvollständig zu sein",
        "Le jeton Discord semble incomplet",
    ),
    "discord_connection_started": _text(
        "Discord connection started",
        "Подключение к Discord запущено",
        "Підключення до Discord розпочато",
        "Discordへの接続を開始しました",
        "已开始连接 Discord",
        "Discord-Verbindung gestartet",
        "Connexion à Discord démarrée",
    ),
    "discord_disconnected": _text(
        "Discord disconnected",
        "Discord отключён",
        "Discord відключено",
        "Discordから切断しました",
        "Discord 已断开",
        "Discord getrennt",
        "Discord déconnecté",
    ),
    "captcha_solution_required": _text(
        "Enter the CAPTCHA solution token",
        "Введите токен решения CAPTCHA",
        "Введіть токен розв’язання CAPTCHA",
        "CAPTCHA解決トークンを入力してください",
        "请输入 CAPTCHA 解决令牌",
        "Geben Sie das CAPTCHA-Lösungstoken ein",
        "Saisissez le jeton de résolution du CAPTCHA",
    ),
    "captcha_expired": _text(
        "The CAPTCHA request expired or was already answered",
        "Запрос CAPTCHA истёк или уже был обработан",
        "Запит CAPTCHA минув або на нього вже відповіли",
        "CAPTCHA要求は期限切れか回答済みです",
        "CAPTCHA 请求已过期或已处理",
        "Die CAPTCHA-Anfrage ist abgelaufen oder wurde bereits beantwortet",
        "La demande de CAPTCHA a expiré ou a déjà reçu une réponse",
    ),
    "captcha_submitted": _text(
        "CAPTCHA solution submitted",
        "Решение CAPTCHA отправлено",
        "Розв’язання CAPTCHA надіслано",
        "CAPTCHA解決情報を送信しました",
        "CAPTCHA 解决方案已提交",
        "CAPTCHA-Lösung übermittelt",
        "Solution du CAPTCHA envoyée",
    ),
    "timezone_invalid": _text(
        "Owner timezone must be a valid IANA timezone name",
        "Часовой пояс владельца должен быть корректным именем IANA",
        "Часовий пояс власника має бути коректною назвою IANA",
        "所有者のタイムゾーンには有効なIANA名を指定してください",
        "所有者时区必须是有效的 IANA 时区名称",
        "Die Zeitzone des Inhabers muss ein gültiger IANA-Name sein",
        "Le fuseau horaire du propriétaire doit être un nom IANA valide",
    ),
    "conversation_default_invalid": _text(
        "Unknown new-conversation default",
        "Неизвестный режим для новых диалогов",
        "Невідомий режим для нових розмов",
        "新しい会話の既定値が不明です",
        "未知的新对话默认设置",
        "Unbekannte Voreinstellung für neue Unterhaltungen",
        "Valeur par défaut inconnue pour les nouvelles conversations",
    ),
    "detect_native_calls_before_enable": _text(
        "Detect and save native function-call support before enabling automation",
        "Определите и сохраните поддержку нативных вызовов функций перед включением автоматизации",
        "Визначте й збережіть підтримку нативних викликів функцій перед увімкненням автоматизації",
        "自動化を有効にする前にネイティブ関数呼び出し対応を検出して保存してください",
        "启用自动化前请检测并保存原生函数调用支持",
        "Erkennen und speichern Sie native Funktionsaufrufe, bevor Sie die Automatisierung aktivieren",
        "Détectez et enregistrez la prise en charge des appels de fonction natifs avant d’activer l’automatisation",
    ),
    "model_name_required": _text(
        "Model name cannot be empty",
        "Название модели не может быть пустым",
        "Назва моделі не може бути порожньою",
        "モデル名は空にできません",
        "模型名称不能为空",
        "Der Modellname darf nicht leer sein",
        "Le nom du modèle ne peut pas être vide",
    ),
    "owner_details_too_long": _text(
        "Owner details cannot exceed 20,000 characters",
        "Сведения о владельце не могут превышать 20 000 символов",
        "Відомості про власника не можуть перевищувати 20 000 символів",
        "所有者情報は20,000文字以内にしてください",
        "所有者详情不能超过 20,000 个字符",
        "Inhaberdetails dürfen 20.000 Zeichen nicht überschreiten",
        "Les détails du propriétaire ne peuvent pas dépasser 20 000 caractères",
    ),
    "minimum_exceeds_maximum": _text(
        "Minimum values cannot exceed maximum values",
        "Минимальные значения не могут превышать максимальные",
        "Мінімальні значення не можуть перевищувати максимальні",
        "最小値は最大値以下にしてください",
        "最小值不能超过最大值",
        "Mindestwerte dürfen Höchstwerte nicht überschreiten",
        "Les valeurs minimales ne peuvent pas dépasser les valeurs maximales",
    ),
    "history_too_short": _text(
        "Provide at least 200 characters of message history",
        "Предоставьте не менее 200 символов истории сообщений",
        "Надайте щонайменше 200 символів історії повідомлень",
        "メッセージ履歴を200文字以上入力してください",
        "请提供至少 200 个字符的消息历史",
        "Geben Sie mindestens 200 Zeichen Nachrichtenverlauf an",
        "Fournissez au moins 200 caractères d’historique de messages",
    ),
    "discord_history_too_short": _text(
        "The selected Discord history did not contain enough human-authored text",
        "В выбранной истории Discord недостаточно текста, написанного человеком",
        "У вибраній історії Discord недостатньо тексту, написаного людиною",
        "選択したDiscord履歴に人が書いたテキストが十分ありません",
        "所选 Discord 历史中人工编写的文本不足",
        "Der ausgewählte Discord-Verlauf enthält nicht genügend von Menschen verfassten Text",
        "L’historique Discord sélectionné ne contient pas assez de texte rédigé par un humain",
    ),
    "personality_too_short": _text(
        "The personality description must be at least 50 characters",
        "Описание личности должно содержать не менее 50 символов",
        "Опис особистості має містити щонайменше 50 символів",
        "人物像の説明は50文字以上にしてください",
        "性格描述须至少 50 个字符",
        "Die Persönlichkeitsbeschreibung muss mindestens 50 Zeichen lang sein",
        "La description de personnalité doit contenir au moins 50 caractères",
    ),
    "personality_updated": _text(
        "Personality updated",
        "Профиль личности обновлён",
        "Профіль особистості оновлено",
        "人物像を更新しました",
        "性格资料已更新",
        "Persönlichkeit aktualisiert",
        "Personnalité mise à jour",
    ),
    "conversation_paused": _text(
        "Automation disabled for this conversation",
        "Автоматизация для этого диалога отключена",
        "Автоматизацію для цієї розмови вимкнено",
        "この会話の自動化を無効にしました",
        "已关闭此对话的自动化",
        "Automatisierung für diese Unterhaltung deaktiviert",
        "Automatisation désactivée pour cette conversation",
    ),
    "conversation_resumed": _text(
        "Automation enabled; the next incoming DM may receive a reply",
        "Автоматизация включена; на следующее входящее личное сообщение может быть дан ответ",
        "Автоматизацію ввімкнено; наступне вхідне приватне повідомлення може отримати відповідь",
        "自動化を有効にしました。次の受信DMに返信する場合があります",
        "已启用自动化；下一条私聊可能会收到回复",
        "Automatisierung aktiviert; die nächste eingehende DM kann beantwortet werden",
        "Automatisation activée ; le prochain MP entrant pourra recevoir une réponse",
    ),
    "connect_provider_before_force": _text(
        "Connect the active model provider before forcing a reply",
        "Подключите активного провайдера модели перед принудительным ответом",
        "Підключіть активного провайдера моделі перед примусовою відповіддю",
        "返信を強制する前に有効なモデルプロバイダーへ接続してください",
        "强制回复前请连接当前模型提供商",
        "Verbinden Sie den aktiven Modellanbieter, bevor Sie eine Antwort erzwingen",
        "Connectez le fournisseur de modèle actif avant de forcer une réponse",
    ),
    "forced_reply_scheduled": _text(
        "Forced reply scheduled",
        "Принудительный ответ запланирован",
        "Примусову відповідь заплановано",
        "強制返信を予約しました",
        "已安排强制回复",
        "Erzwungene Antwort eingeplant",
        "Réponse forcée planifiée",
    ),
    "escalation_not_found": _text(
        "Escalation was not found or is already closed",
        "Обращение не найдено или уже закрыто",
        "Звернення не знайдено або вже закрито",
        "エスカレーションが見つからないか、すでに終了しています",
        "转交请求未找到或已关闭",
        "Weiterleitung nicht gefunden oder bereits geschlossen",
        "Transfert introuvable ou déjà fermé",
    ),
    "escalation_claimed": _text(
        "Escalation claimed",
        "Обращение принято в работу",
        "Звернення взято в роботу",
        "エスカレーションを引き受けました",
        "已认领转交请求",
        "Weiterleitung übernommen",
        "Transfert pris en charge",
    ),
    "escalation_resolved": _text(
        "Escalation resolved",
        "Обращение решено",
        "Звернення вирішено",
        "エスカレーションを解決しました",
        "转交请求已解决",
        "Weiterleitung gelöst",
        "Transfert résolu",
    ),
    "escalation_dismissed": _text(
        "Escalation dismissed",
        "Обращение отклонено",
        "Звернення відхилено",
        "エスカレーションを却下しました",
        "转交请求已忽略",
        "Weiterleitung verworfen",
        "Transfert ignoré",
    ),
    "automation_resumed_suffix": _text(
        " and automation resumed",
        " и автоматизация возобновлена",
        " й автоматизацію відновлено",
        "。自動化も再開しました",
        "，自动化已恢复",
        " und Automatisierung fortgesetzt",
        " et automatisation reprise",
    ),
    "delete_confirmation_required": _text(
        "Confirm the row deletion before submitting",
        "Подтвердите удаление строки перед отправкой",
        "Підтвердьте видалення рядка перед надсиланням",
        "送信前に行の削除を確認してください",
        "提交前请确认删除该行",
        "Bestätigen Sie das Löschen der Zeile vor dem Absenden",
        "Confirmez la suppression de la ligne avant l’envoi",
    ),
    "database_row_not_found": _text(
        "Database row was not found",
        "Строка базы данных не найдена",
        "Рядок бази даних не знайдено",
        "データベース行が見つかりません",
        "未找到数据库行",
        "Datenbankzeile nicht gefunden",
        "Ligne de base de données introuvable",
    ),
    "database_row_deleted": _text(
        "Deleted row {row} from {table}",
        "Строка {row} удалена из {table}",
        "Рядок {row} видалено з {table}",
        "{table}から行{row}を削除しました",
        "已从 {table} 删除行 {row}",
        "Zeile {row} aus {table} gelöscht",
        "Ligne {row} supprimée de {table}",
    ),
    "personality_cached": _text(
        "This message history is already cached; no model call was made",
        "Эта история сообщений уже закэширована; модель не вызывалась",
        "Цю історію повідомлень уже закешовано; модель не викликалася",
        "このメッセージ履歴はキャッシュ済みのため、モデルは呼び出していません",
        "此消息历史已缓存；未调用模型",
        "Dieser Nachrichtenverlauf ist bereits zwischengespeichert; das Modell wurde nicht aufgerufen",
        "Cet historique est déjà en cache ; aucun appel au modèle n’a été effectué",
    ),
    "personality_inferred": _text(
        "Personality inferred and cached",
        "Профиль личности выведен и закэширован",
        "Профіль особистості виведено й закешовано",
        "人物像を推定してキャッシュしました",
        "已推断并缓存性格资料",
        "Persönlichkeit abgeleitet und zwischengespeichert",
        "Personnalité déduite et mise en cache",
    ),
    "source_pasted_history": _text(
        "Pasted history",
        "Вставленная история",
        "Вставлена історія",
        "貼り付けた履歴",
        "粘贴的历史",
        "Eingefügter Verlauf",
        "Historique collé",
    ),
    "source_discord_history": _text(
        "Discord history",
        "История Discord",
        "Історія Discord",
        "Discord履歴",
        "Discord 历史",
        "Discord-Verlauf",
        "Historique Discord",
    ),
    "source_edited": _text(
        "Edited", "Отредактировано", "Відредаговано", "編集済み", "已编辑", "Bearbeitet", "Modifié"
    ),
    "custom_provider_native_required": _text(
        "The custom provider must pass native function-call detection before automation.",
        "Пользовательский провайдер должен пройти проверку нативных вызовов функций перед автоматизацией.",
        "Користувацький провайдер має пройти перевірку нативних викликів функцій перед автоматизацією.",
        "自動化の前にカスタムプロバイダーがネイティブ関数呼び出し検出に合格する必要があります。",
        "自定义提供商必须通过原生函数调用检测后才能启用自动化。",
        "Der benutzerdefinierte Anbieter muss vor der Automatisierung die Erkennung nativer Funktionsaufrufe bestehen.",
        "Le fournisseur personnalisé doit réussir la détection des appels de fonction natifs avant l’automatisation.",
    ),
    "cross_origin_rejected": _text(
        "Cross-origin form submission rejected; expected {url}",
        "Межсайтовая отправка формы отклонена; ожидается {url}",
        "Міжсайтове надсилання форми відхилено; очікується {url}",
        "別オリジンからのフォーム送信を拒否しました。想定URL：{url}",
        "已拒绝跨源表单提交；预期来源为 {url}",
        "Formularübermittlung fremder Herkunft abgelehnt; erwartet wurde {url}",
        "Envoi de formulaire interorigine refusé ; origine attendue : {url}",
    ),
    "api_base_url_invalid": _text(
        "API base URL must be an absolute HTTP(S) URL without credentials or a query",
        "Базовый URL API должен быть абсолютным HTTP(S)-адресом без учётных данных и строки запроса",
        "Базова URL-адреса API має бути абсолютною HTTP(S)-адресою без облікових даних і рядка запиту",
        "APIベースURLには認証情報やクエリを含まない絶対HTTP(S) URLを指定してください",
        "API 基础 URL 必须是绝对 HTTP(S) URL，且不能包含凭据或查询字符串",
        "Die API-Basis-URL muss eine absolute HTTP(S)-URL ohne Zugangsdaten oder Abfrage sein",
        "L’URL de base de l’API doit être une URL HTTP(S) absolue, sans identifiants ni requête",
    ),
    "database_table_unknown": _text(
        "Unknown database table",
        "Неизвестная таблица базы данных",
        "Невідома таблиця бази даних",
        "不明なデータベーステーブルです",
        "未知数据库表",
        "Unbekannte Datenbanktabelle",
        "Table de base de données inconnue",
    ),
    "database_table_read_only": _text(
        "This database table is read-only",
        "Эта таблица базы данных доступна только для чтения",
        "Ця таблиця бази даних доступна лише для читання",
        "このデータベーステーブルは読み取り専用です",
        "此数据库表为只读",
        "Diese Datenbanktabelle ist schreibgeschützt",
        "Cette table de base de données est en lecture seule",
    ),
    "discord_required_force": _text(
        "Discord must be connected before forcing a reply",
        "Подключите Discord перед принудительным ответом",
        "Підключіть Discord перед примусовою відповіддю",
        "返信を強制する前にDiscordへ接続してください",
        "强制回复前必须连接 Discord",
        "Discord muss verbunden sein, bevor eine Antwort erzwungen wird",
        "Discord doit être connecté avant de forcer une réponse",
    ),
    "discord_channel_invalid": _text(
        "Invalid Discord channel ID",
        "Некорректный идентификатор канала Discord",
        "Некоректний ідентифікатор каналу Discord",
        "DiscordチャンネルIDが無効です",
        "Discord 频道 ID 无效",
        "Ungültige Discord-Kanal-ID",
        "Identifiant de canal Discord invalide",
    ),
    "discord_conversation_unavailable": _text(
        "Discord conversation is not available",
        "Диалог Discord недоступен",
        "Розмова Discord недоступна",
        "Discordの会話を利用できません",
        "Discord 对话不可用",
        "Discord-Unterhaltung ist nicht verfügbar",
        "La conversation Discord n’est pas disponible",
    ),
    "discord_no_incoming_message": _text(
        "This conversation has no incoming message to answer",
        "В этом диалоге нет входящего сообщения, на которое можно ответить",
        "У цій розмові немає вхідного повідомлення, на яке можна відповісти",
        "この会話には返信できる受信メッセージがありません",
        "此对话中没有可回复的传入消息",
        "Diese Unterhaltung enthält keine eingehende Nachricht zum Beantworten",
        "Cette conversation ne contient aucun message entrant auquel répondre",
    ),
    "discord_message_id_invalid": _text(
        "The latest incoming Discord message ID is invalid",
        "Идентификатор последнего входящего сообщения Discord некорректен",
        "Ідентифікатор останнього вхідного повідомлення Discord некоректний",
        "最新の受信DiscordメッセージIDが無効です",
        "最新传入 Discord 消息的 ID 无效",
        "Die ID der letzten eingehenden Discord-Nachricht ist ungültig",
        "L’identifiant du dernier message Discord entrant est invalide",
    ),
    "discord_required_history": _text(
        "Discord must be connected before loading message history",
        "Подключите Discord перед загрузкой истории сообщений",
        "Підключіть Discord перед завантаженням історії повідомлень",
        "メッセージ履歴を読み込む前にDiscordへ接続してください",
        "加载消息历史前必须连接 Discord",
        "Discord muss verbunden sein, bevor der Nachrichtenverlauf geladen wird",
        "Discord doit être connecté avant de charger l’historique des messages",
    ),
    "assistant_tab": _text(
        "Assistant", "Ассистент", "Асистент", "アシスタント", "助手", "Assistent", "Assistant"
    ),
    "appearance": _text("Appearance", "Оформление", "Вигляд", "外観", "外观", "Darstellung", "Apparence"),
    "theme": _text("Theme", "Тема", "Тема", "テーマ", "主题", "Design", "Thème"),
    "theme_system": _text("System", "Системная", "Системна", "システム", "跟随系统", "System", "Système"),
    "theme_light": _text("Light", "Светлая", "Світла", "ライト", "浅色", "Hell", "Clair"),
    "theme_dark": _text("Dark", "Тёмная", "Темна", "ダーク", "深色", "Dunkel", "Sombre"),
    "theme_black": _text(
        "Black (OLED)",
        "Чёрная (OLED)",
        "Чорна (OLED)",
        "ブラック（OLED）",
        "纯黑（OLED）",
        "Schwarz (OLED)",
        "Noir (OLED)",
    ),
    "apply_theme": _text("Apply", "Применить", "Застосувати", "適用", "应用", "Anwenden", "Appliquer"),
    "theme_saved": _text(
        "Theme updated",
        "Тема обновлена",
        "Тему оновлено",
        "テーマを更新しました",
        "主题已更新",
        "Design aktualisiert",
        "Thème mis à jour",
    ),
    "unknown_theme": _text(
        "Unknown interface theme",
        "Неизвестная тема интерфейса",
        "Невідома тема інтерфейсу",
        "不明なインターフェーステーマです",
        "未知界面主题",
        "Unbekanntes Oberflächendesign",
        "Thème d’interface inconnu",
    ),
    "mode_automatic": _text(
        "Automatic", "Автоматический", "Автоматичний", "自動", "自动", "Automatisch", "Automatique"
    ),
    "mode_inline": _text(
        "Inline collaboration",
        "Совместное участие",
        "Спільна участь",
        "インライン共同",
        "内联协作",
        "Inline-Zusammenarbeit",
        "Collaboration intégrée",
    ),
    "mode_paused": _text(
        "Paused", "Приостановлен", "Призупинено", "一時停止", "已暂停", "Pausiert", "En pause"
    ),
    "conversation_mode": _text("Mode", "Режим", "Режим", "モード", "模式", "Modus", "Mode"),
    "inline_mode_help": _text(
        "In inline mode, the assistant may help after messages from either participant, stays silent when it has nothing useful to add, and always marks its replies with 🤖.",
        "В режиме совместного участия ассистент может помогать после сообщений любого собеседника, молчит, если ему нечего добавить, и всегда помечает ответы 🤖.",
        "У режимі спільної участі асистент може допомагати після повідомлень будь-якого співрозмовника, мовчить, якщо йому нічого додати, і завжди позначає відповіді 🤖.",
        "インライン共同モードでは、どちらの参加者のメッセージ後にも必要に応じて支援し、付け加えることがなければ沈黙し、返信には常に🤖を付けます。",
        "在内联协作模式下，助手可在任一参与者发言后提供帮助，无有用补充时保持沉默，并始终用 🤖 标记回复。",
        "Im Inline-Modus kann der Assistent nach Nachrichten beider Beteiligten helfen, bleibt ohne nützlichen Beitrag still und kennzeichnet seine Antworten immer mit 🤖.",
        "En mode intégré, l’assistant peut aider après les messages des deux interlocuteurs, reste silencieux sans contribution utile et marque toujours ses réponses avec 🤖.",
    ),
    "conversation_mode_saved": _text(
        "Conversation mode updated",
        "Режим диалога обновлён",
        "Режим розмови оновлено",
        "会話モードを更新しました",
        "对话模式已更新",
        "Unterhaltungsmodus aktualisiert",
        "Mode de conversation mis à jour",
    ),
    "conversation_mode_invalid": _text(
        "Unknown conversation mode",
        "Неизвестный режим диалога",
        "Невідомий режим розмови",
        "不明な会話モードです",
        "未知对话模式",
        "Unbekannter Unterhaltungsmodus",
        "Mode de conversation inconnu",
    ),
    "conversation_not_found": _text(
        "Conversation was not found",
        "Диалог не найден",
        "Розмову не знайдено",
        "会話が見つかりません",
        "未找到对话",
        "Unterhaltung nicht gefunden",
        "Conversation introuvable",
    ),
    "save": _text("Save", "Сохранить", "Зберегти", "保存", "保存", "Speichern", "Enregistrer"),
    "assistant_name": _text(
        "Assistant name",
        "Имя ассистента",
        "Ім’я асистента",
        "アシスタント名",
        "助手名称",
        "Name des Assistenten",
        "Nom de l’assistant",
    ),
    "assistant_name_help": _text(
        "Leave blank to use the localized name {name}.",
        "Оставьте пустым, чтобы использовать локализованное имя {name}.",
        "Залиште порожнім, щоб використовувати локалізоване ім’я {name}.",
        "空欄の場合はローカライズ名「{name}」を使います。",
        "留空将使用本地化名称“{name}”。",
        "Leer lassen, um den lokalisierten Namen {name} zu verwenden.",
        "Laissez vide pour utiliser le nom localisé {name}.",
    ),
    "assistant_name_invalid": _text(
        "Assistant name must contain at most 80 printable characters",
        "Имя ассистента должно содержать не более 80 печатных символов",
        "Ім’я асистента має містити не більше 80 друкованих символів",
        "アシスタント名は印刷可能な80文字以内にしてください",
        "助手名称最多可包含 80 个可打印字符",
        "Der Assistentenname darf höchstens 80 druckbare Zeichen enthalten",
        "Le nom de l’assistant doit contenir au maximum 80 caractères imprimables",
    ),
}


def ui_text(locale: str, key: str, **values: object) -> str:
    translations = UI_TEXT.get(key)
    if translations is None:
        return key
    text = translations.get(normalize_locale(locale), translations["en"])
    return text.format(**values) if values else text
