from __future__ import annotations

from .localization import normalize_locale


# Short, stable keys keep translations out of the Jinja template and make missing
# translations fall back to English instead of breaking the admin page.
UI_TEXT: dict[str, dict[str, str]] = {
    "skip": {
        "en": "Skip to content",
        "ru": "Перейти к содержимому",
        "uk": "Перейти до вмісту",
        "ja": "コンテンツへ移動",
        "de": "Zum Inhalt springen",
        "fr": "Aller au contenu",
    },
    "admin_navigation": {
        "en": "Admin navigation",
        "ru": "Навигация администратора",
        "uk": "Навігація адміністратора",
        "ja": "管理画面ナビゲーション",
        "de": "Admin-Navigation",
        "fr": "Navigation d’administration",
    },
    "connections": {
        "en": "Connections",
        "ru": "Подключения",
        "uk": "Підключення",
        "ja": "接続",
        "de": "Verbindungen",
        "fr": "Connexions",
    },
    "personality": {
        "en": "Personality",
        "ru": "Личность",
        "uk": "Особистість",
        "ja": "人物像",
        "de": "Persönlichkeit",
        "fr": "Personnalité",
    },
    "behavior": {
        "en": "Behavior",
        "ru": "Поведение",
        "uk": "Поведінка",
        "ja": "動作",
        "de": "Verhalten",
        "fr": "Comportement",
    },
    "usage": {
        "en": "Usage",
        "ru": "Использование",
        "uk": "Використання",
        "ja": "使用状況",
        "de": "Nutzung",
        "fr": "Utilisation",
    },
    "conversations": {
        "en": "Conversations",
        "ru": "Диалоги",
        "uk": "Розмови",
        "ja": "会話",
        "de": "Unterhaltungen",
        "fr": "Conversations",
    },
    "database": {
        "en": "Database",
        "ru": "База данных",
        "uk": "База даних",
        "ja": "データベース",
        "de": "Datenbank",
        "fr": "Base de données",
    },
    "tagline_label": {
        "en": "Private DM automation",
        "ru": "Автоматизация личных сообщений",
        "uk": "Автоматизація приватних повідомлень",
        "ja": "DM自動化",
        "de": "Automatisierung privater Nachrichten",
        "fr": "Automatisation des messages privés",
    },
    "tagline": {
        "en": "Natural replies that step aside whenever you join the conversation.",
        "ru": "Естественные ответы, которые уступают место, когда вы вступаете в разговор.",
        "uk": "Природні відповіді, що поступаються місцем, коли ви долучаєтеся до розмови.",
        "ja": "あなたが会話に加わると、自動返信は自然に止まります。",
        "de": "Natürliche Antworten, die pausieren, sobald du dich einschaltest.",
        "fr": "Des réponses naturelles qui s’effacent dès que vous rejoignez la conversation.",
    },
    "automation_enabled": {
        "en": "Automation enabled",
        "ru": "Автоматизация включена",
        "uk": "Автоматизацію ввімкнено",
        "ja": "自動化は有効です",
        "de": "Automatisierung aktiviert",
        "fr": "Automatisation activée",
    },
    "automation_disabled": {
        "en": "Automation disabled",
        "ru": "Автоматизация выключена",
        "uk": "Автоматизацію вимкнено",
        "ja": "自動化は無効です",
        "de": "Automatisierung deaktiviert",
        "fr": "Automatisation désactivée",
    },
    "active": {
        "en": "Active",
        "ru": "Активно",
        "uk": "Активно",
        "ja": "使用中",
        "de": "Aktiv",
        "fr": "Actif",
    },
    "connected": {
        "en": "Connected",
        "ru": "Подключено",
        "uk": "Підключено",
        "ja": "接続済み",
        "de": "Verbunden",
        "fr": "Connecté",
    },
    "not_connected": {
        "en": "Not connected",
        "ru": "Не подключено",
        "uk": "Не підключено",
        "ja": "未接続",
        "de": "Nicht verbunden",
        "fr": "Non connecté",
    },
    "configured": {
        "en": "Configured",
        "ru": "Настроено",
        "uk": "Налаштовано",
        "ja": "設定済み",
        "de": "Konfiguriert",
        "fr": "Configuré",
    },
    "not_configured": {
        "en": "Not configured",
        "ru": "Не настроено",
        "uk": "Не налаштовано",
        "ja": "未設定",
        "de": "Nicht konfiguriert",
        "fr": "Non configuré",
    },
    "chatgpt_subscription": {
        "en": "ChatGPT subscription",
        "ru": "Подписка ChatGPT",
        "uk": "Підписка ChatGPT",
        "ja": "ChatGPTサブスクリプション",
        "de": "ChatGPT-Abonnement",
        "fr": "Abonnement ChatGPT",
    },
    "custom_api": {
        "en": "OpenAI-compatible API",
        "ru": "OpenAI-совместимый API",
        "uk": "OpenAI-сумісний API",
        "ja": "OpenAI互換API",
        "de": "OpenAI-kompatible API",
        "fr": "API compatible OpenAI",
    },
    "discord": {
        "en": "Discord",
        "ru": "Discord",
        "uk": "Discord",
        "ja": "Discord",
        "de": "Discord",
        "fr": "Discord",
    },
    "disconnect": {
        "en": "Disconnect",
        "ru": "Отключить",
        "uk": "Відключити",
        "ja": "切断",
        "de": "Trennen",
        "fr": "Déconnecter",
    },
    "sign_in_chatgpt": {
        "en": "Sign in with ChatGPT",
        "ru": "Войти через ChatGPT",
        "uk": "Увійти через ChatGPT",
        "ja": "ChatGPTでログイン",
        "de": "Mit ChatGPT anmelden",
        "fr": "Se connecter avec ChatGPT",
    },
    "save_connect": {
        "en": "Save token and connect",
        "ru": "Сохранить токен и подключиться",
        "uk": "Зберегти токен і підключитися",
        "ja": "トークンを保存して接続",
        "de": "Token speichern und verbinden",
        "fr": "Enregistrer le jeton et se connecter",
    },
    "personality_cache": {
        "en": "Personality cache",
        "ru": "Кэш личности",
        "uk": "Кеш особистості",
        "ja": "人物像キャッシュ",
        "de": "Persönlichkeits-Cache",
        "fr": "Cache de personnalité",
    },
    "cached": {
        "en": "Cached",
        "ru": "Сохранено",
        "uk": "Збережено",
        "ja": "保存済み",
        "de": "Gespeichert",
        "fr": "En cache",
    },
    "empty": {"en": "Empty", "ru": "Пусто", "uk": "Порожньо", "ja": "空", "de": "Leer", "fr": "Vide"},
    "reply_behavior": {
        "en": "Reply behavior",
        "ru": "Поведение ответов",
        "uk": "Поведінка відповідей",
        "ja": "返信動作",
        "de": "Antwortverhalten",
        "fr": "Comportement des réponses",
    },
    "admin_language": {
        "en": "Admin interface language",
        "ru": "Язык панели администратора",
        "uk": "Мова панелі адміністратора",
        "ja": "管理画面の言語",
        "de": "Sprache der Admin-Oberfläche",
        "fr": "Langue de l’interface d’administration",
    },
    "prompt_language": {
        "en": "Built-in prompt language",
        "ru": "Язык встроенных промптов",
        "uk": "Мова вбудованих промптів",
        "ja": "組み込みプロンプトの言語",
        "de": "Sprache der integrierten Prompts",
        "fr": "Langue des prompts intégrés",
    },
    "prompt_language_help": {
        "en": "Controls built-in assistant, reaction, attachment, and personality prompts. Custom base instructions are preserved.",
        "ru": "Определяет язык встроенных инструкций ассистента, реакций, вложений и профиля. Пользовательские базовые инструкции сохраняются.",
        "uk": "Визначає мову вбудованих інструкцій асистента, реакцій, вкладень і профілю. Власні базові інструкції зберігаються.",
        "ja": "アシスタント、リアクション、添付、人物像の組み込みプロンプトに使います。独自の基本指示は保持されます。",
        "de": "Steuert die integrierten Assistenten-, Reaktions-, Anhangs- und Persönlichkeits-Prompts. Eigene Basisanweisungen bleiben erhalten.",
        "fr": "Contrôle les prompts intégrés de l’assistant, des réactions, des pièces jointes et de la personnalité. Les instructions personnalisées sont conservées.",
    },
    "enable_replies": {
        "en": "Enable automated replies",
        "ru": "Включить автоматические ответы",
        "uk": "Увімкнути автоматичні відповіді",
        "ja": "自動返信を有効にする",
        "de": "Automatische Antworten aktivieren",
        "fr": "Activer les réponses automatiques",
    },
    "silent_replies": {
        "en": "Send generated replies without notifications",
        "ru": "Отправлять ответы без уведомлений",
        "uk": "Надсилати відповіді без сповіщень",
        "ja": "通知なしで返信を送信",
        "de": "Generierte Antworten ohne Benachrichtigung senden",
        "fr": "Envoyer les réponses sans notification",
    },
    "robot_prefix": {
        "en": "Prefix generated replies with 🤖",
        "ru": "Добавлять 🤖 перед ответами",
        "uk": "Додавати 🤖 перед відповідями",
        "ja": "返信の先頭に🤖を付ける",
        "de": "Generierten Antworten 🤖 voranstellen",
        "fr": "Préfixer les réponses avec 🤖",
    },
    "new_conversation_default": {
        "en": "New conversation default",
        "ru": "Настройка новых диалогов",
        "uk": "Налаштування нових розмов",
        "ja": "新しい会話の既定値",
        "de": "Standard für neue Unterhaltungen",
        "fr": "Valeur par défaut des nouvelles conversations",
    },
    "provider": {
        "en": "Provider",
        "ru": "Провайдер",
        "uk": "Провайдер",
        "ja": "プロバイダー",
        "de": "Anbieter",
        "fr": "Fournisseur",
    },
    "model": {"en": "Model", "ru": "Модель", "uk": "Модель", "ja": "モデル", "de": "Modell", "fr": "Modèle"},
    "reasoning": {
        "en": "Reasoning",
        "ru": "Рассуждение",
        "uk": "Міркування",
        "ja": "推論",
        "de": "Schlussfolgern",
        "fr": "Raisonnement",
    },
    "reply_token_budget": {
        "en": "Reply token budget",
        "ru": "Лимит токенов ответа",
        "uk": "Ліміт токенів відповіді",
        "ja": "返信トークン上限",
        "de": "Tokenbudget der Antwort",
        "fr": "Budget de jetons de réponse",
    },
    "multi_message_replies": {
        "en": "Multi-message replies",
        "ru": "Ответы из нескольких сообщений",
        "uk": "Відповіді з кількох повідомлень",
        "ja": "複数メッセージ返信",
        "de": "Antworten mit mehreren Nachrichten",
        "fr": "Réponses en plusieurs messages",
    },
    "reply_timing": {
        "en": "Reply timing",
        "ru": "Время ответа",
        "uk": "Час відповіді",
        "ja": "返信タイミング",
        "de": "Antwortzeit",
        "fr": "Temporisation des réponses",
    },
    "quiet_window": {
        "en": "Human activity quiet window",
        "ru": "Пауза после активности человека",
        "uk": "Пауза після активності людини",
        "ja": "手動操作後の休止時間",
        "de": "Ruhefenster nach menschlicher Aktivität",
        "fr": "Pause après une activité humaine",
    },
    "owner_details": {
        "en": "Owner details",
        "ru": "Данные владельца",
        "uk": "Дані власника",
        "ja": "所有者の情報",
        "de": "Angaben zum Inhaber",
        "fr": "Informations sur le propriétaire",
    },
    "base_instructions": {
        "en": "Base instructions",
        "ru": "Базовые инструкции",
        "uk": "Базові інструкції",
        "ja": "基本指示",
        "de": "Basisanweisungen",
        "fr": "Instructions de base",
    },
    "save_behavior": {
        "en": "Save behavior",
        "ru": "Сохранить настройки",
        "uk": "Зберегти налаштування",
        "ja": "動作設定を保存",
        "de": "Verhalten speichern",
        "fr": "Enregistrer le comportement",
    },
    "model_token_usage": {
        "en": "Model token usage",
        "ru": "Использование токенов",
        "uk": "Використання токенів",
        "ja": "モデルのトークン使用量",
        "de": "Token-Nutzung des Modells",
        "fr": "Utilisation des jetons du modèle",
    },
    "force_reply": {
        "en": "Force reply",
        "ru": "Ответить принудительно",
        "uk": "Відповісти примусово",
        "ja": "強制返信",
        "de": "Antwort erzwingen",
        "fr": "Forcer une réponse",
    },
    "enable_automation": {
        "en": "Enable automation",
        "ru": "Включить автоматизацию",
        "uk": "Увімкнути автоматизацію",
        "ja": "自動化を有効にする",
        "de": "Automatisierung aktivieren",
        "fr": "Activer l’automatisation",
    },
    "disable_automation": {
        "en": "Disable automation",
        "ru": "Отключить автоматизацию",
        "uk": "Вимкнути автоматизацію",
        "ja": "自動化を無効にする",
        "de": "Automatisierung deaktivieren",
        "fr": "Désactiver l’automatisation",
    },
    "database_explorer": {
        "en": "Database explorer",
        "ru": "Обзор базы данных",
        "uk": "Огляд бази даних",
        "ja": "データベース参照",
        "de": "Datenbank-Explorer",
        "fr": "Explorateur de base de données",
    },
    "search": {
        "en": "Search",
        "ru": "Поиск",
        "uk": "Пошук",
        "ja": "検索",
        "de": "Suchen",
        "fr": "Rechercher",
    },
    "clear": {
        "en": "Clear",
        "ru": "Очистить",
        "uk": "Очистити",
        "ja": "クリア",
        "de": "Leeren",
        "fr": "Effacer",
    },
    "previous": {
        "en": "Previous",
        "ru": "Назад",
        "uk": "Назад",
        "ja": "前へ",
        "de": "Zurück",
        "fr": "Précédent",
    },
    "next": {"en": "Next", "ru": "Далее", "uk": "Далі", "ja": "次へ", "de": "Weiter", "fr": "Suivant"},
    "settings_saved": {
        "en": "Automation settings saved",
        "ru": "Настройки автоматизации сохранены",
        "uk": "Налаштування автоматизації збережено",
        "ja": "自動化設定を保存しました",
        "de": "Automatisierungseinstellungen gespeichert",
        "fr": "Paramètres d’automatisation enregistrés",
    },
    "unknown_locale": {
        "en": "Unknown localization language",
        "ru": "Неизвестный язык локализации",
        "uk": "Невідома мова локалізації",
        "ja": "不明なローカライズ言語です",
        "de": "Unbekannte Lokalisierungssprache",
        "fr": "Langue de localisation inconnue",
    },
}


def ui_text(locale: str, key: str, **values: object) -> str:
    translations = UI_TEXT.get(key)
    if translations is None:
        return key
    text = translations.get(normalize_locale(locale), translations["en"])
    return text.format(**values) if values else text
